/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {}

export interface NexusGenEnums {}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenRootTypes {
  ALXAXBKq: {
    // root type
    id41?: string | null // ID
  }
  AOogKhAD: {
    // root type
    id53?: string | null // ID
  }
  AQDzZPsI: {
    // root type
    id193?: string | null // ID
  }
  ApAniugk: {
    // root type
    id51?: string | null // ID
  }
  AuMxHAoX: {
    // root type
    id146?: string | null // ID
  }
  BAzfAeMR: {
    // root type
    id191?: string | null // ID
  }
  BFohGIGQ: {
    // root type
    id286?: string | null // ID
  }
  BTIsXTrL: {
    // root type
    id250?: string | null // ID
  }
  BWwxnXpM: {
    // root type
    id294?: string | null // ID
  }
  BXowGvwZ: {
    // root type
    id63?: string | null // ID
  }
  BYPWzETJ: {
    // root type
    id266?: string | null // ID
  }
  BiZjyuaY: {
    // root type
    id25?: string | null // ID
  }
  Bjgguvhd: {
    // root type
    id170?: string | null // ID
  }
  CCXSFsMn: {
    // root type
    id268?: string | null // ID
  }
  CXumheDD: {
    // root type
    id172?: string | null // ID
  }
  CgAQHanX: {
    // root type
    id96?: string | null // ID
  }
  DBZLsxpr: {
    // root type
    id137?: string | null // ID
  }
  DGxuhtpo: {
    // root type
    id219?: string | null // ID
  }
  DKEJFUiy: {
    // root type
    id295?: string | null // ID
  }
  DMggicLd: {
    // root type
    id239?: string | null // ID
  }
  DNohRdIN: {
    // root type
    id203?: string | null // ID
  }
  DbgPTfDo: {
    // root type
    id254?: string | null // ID
  }
  DkoAlvGn: {
    // root type
    id282?: string | null // ID
  }
  DpnWHIJW: {
    // root type
    id7?: string | null // ID
  }
  ECChhDfK: {
    // root type
    id79?: string | null // ID
  }
  ETUiuOHD: {
    // root type
    id35?: string | null // ID
  }
  EhpNnQJw: {
    // root type
    id121?: string | null // ID
  }
  EjIQIfmv: {
    // root type
    id126?: string | null // ID
  }
  EqEZXLCy: {
    // root type
    id30?: string | null // ID
  }
  EtPHwkkm: {
    // root type
    id57?: string | null // ID
  }
  EzcWBhIv: {
    // root type
    id214?: string | null // ID
  }
  FDouQoXO: {
    // root type
    id173?: string | null // ID
  }
  FHLtgKoA: {
    // root type
    id258?: string | null // ID
  }
  FaJAYKqm: {
    // root type
    id93?: string | null // ID
  }
  FcFlCNAk: {
    // root type
    id228?: string | null // ID
  }
  FvftqquW: {
    // root type
    id281?: string | null // ID
  }
  GDATeumz: {
    // root type
    id256?: string | null // ID
  }
  GYbaqoRT: {
    // root type
    id105?: string | null // ID
  }
  GcpbGXTn: {
    // root type
    id218?: string | null // ID
  }
  GdxXCAak: {
    // root type
    id13?: string | null // ID
  }
  GhHKLcZe: {
    // root type
    id199?: string | null // ID
  }
  GsbHZkLK: {
    // root type
    id34?: string | null // ID
  }
  GwkBnXKj: {
    // root type
    id207?: string | null // ID
  }
  GzglazdH: {
    // root type
    id95?: string | null // ID
  }
  HENcJewx: {
    // root type
    id185?: string | null // ID
  }
  HIPZQFdS: {
    // root type
    id251?: string | null // ID
  }
  HJmsvtgX: {
    // root type
    id151?: string | null // ID
  }
  HLRWzsTU: {
    // root type
    id182?: string | null // ID
  }
  HNLQTErw: {
    // root type
    id155?: string | null // ID
  }
  HWMyawvm: {
    // root type
    id187?: string | null // ID
  }
  HXZUTyvG: {
    // root type
    id46?: string | null // ID
  }
  HZbsVdoX: {
    // root type
    id68?: string | null // ID
  }
  HdiyXGxs: {
    // root type
    id178?: string | null // ID
  }
  HgYVPDgm: {
    // root type
    id87?: string | null // ID
  }
  HjRDJhnX: {
    // root type
    id133?: string | null // ID
  }
  HwkXtjRP: {
    // root type
    id84?: string | null // ID
  }
  HxCkBUxv: {
    // root type
    id192?: string | null // ID
  }
  IAOEaBfb: {
    // root type
    id120?: string | null // ID
  }
  IBZxPcZb: {
    // root type
    id205?: string | null // ID
  }
  ICrkovFe: {
    // root type
    id73?: string | null // ID
  }
  IGibGxHO: {
    // root type
    id204?: string | null // ID
  }
  ISayJMYD: {
    // root type
    id129?: string | null // ID
  }
  IWhegzTM: {
    // root type
    id43?: string | null // ID
  }
  IZERvBgk: {
    // root type
    id32?: string | null // ID
  }
  IhSGxaNc: {
    // root type
    id103?: string | null // ID
  }
  IhtaZNUi: {
    // root type
    id238?: string | null // ID
  }
  IqZAiUKE: {
    // root type
    id223?: string | null // ID
  }
  IuVQPFJN: {
    // root type
    id152?: string | null // ID
  }
  Iypygftg: {
    // root type
    id77?: string | null // ID
  }
  JXAbemqC: {
    // root type
    id153?: string | null // ID
  }
  JZMQpjQv: {
    // root type
    id125?: string | null // ID
  }
  JbsCxxcE: {
    // root type
    id8?: string | null // ID
  }
  JjkgZKrV: {
    // root type
    id202?: string | null // ID
  }
  JsAPYbRs: {
    // root type
    id156?: string | null // ID
  }
  JuaucwDY: {
    // root type
    id134?: string | null // ID
  }
  KGbJMfhO: {
    // root type
    id159?: string | null // ID
  }
  KVIgujkc: {
    // root type
    id157?: string | null // ID
  }
  KbTYPbTr: {
    // root type
    id92?: string | null // ID
  }
  KoKtAqbt: {
    // root type
    id213?: string | null // ID
  }
  KsPfaUFr: {
    // root type
    id86?: string | null // ID
  }
  KvHHVcPa: {
    // root type
    id147?: string | null // ID
  }
  LBePcCkW: {
    // root type
    id112?: string | null // ID
  }
  LHxWkxKq: {
    // root type
    id64?: string | null // ID
  }
  LMnZbpCI: {
    // root type
    id106?: string | null // ID
  }
  LtvKCzwe: {
    // root type
    id19?: string | null // ID
  }
  MPQLFUho: {
    // root type
    id31?: string | null // ID
  }
  MvpRfuhb: {
    // root type
    id198?: string | null // ID
  }
  NETQHyFQ: {
    // root type
    id55?: string | null // ID
  }
  NbTtwcUU: {
    // root type
    id0?: string | null // ID
  }
  NczZcGdE: {
    // root type
    id209?: string | null // ID
  }
  NefQmhqG: {
    // root type
    id149?: string | null // ID
  }
  NlMnyCgu: {
    // root type
    id162?: string | null // ID
  }
  NrrBYDim: {
    // root type
    id163?: string | null // ID
  }
  NwPaWUGr: {
    // root type
    id292?: string | null // ID
  }
  OBnGIgyZ: {
    // root type
    id242?: string | null // ID
  }
  OZfGULVa: {
    // root type
    id195?: string | null // ID
  }
  OehdOjXt: {
    // root type
    id278?: string | null // ID
  }
  OfyEZrPd: {
    // root type
    id21?: string | null // ID
  }
  OjwpvBGH: {
    // root type
    id227?: string | null // ID
  }
  OwZeKGSU: {
    // root type
    id128?: string | null // ID
  }
  PBGQfXYx: {
    // root type
    id83?: string | null // ID
  }
  PGcwRfdb: {
    // root type
    id62?: string | null // ID
  }
  PHltFHbS: {
    // root type
    id226?: string | null // ID
  }
  PNeiVzWR: {
    // root type
    id113?: string | null // ID
  }
  PNgZWWwo: {
    // root type
    id148?: string | null // ID
  }
  PTtcHGFZ: {
    // root type
    id114?: string | null // ID
  }
  PVCfSccj: {
    // root type
    id224?: string | null // ID
  }
  PWOXDRzE: {
    // root type
    id56?: string | null // ID
  }
  PYCDIQQc: {
    // root type
    id24?: string | null // ID
  }
  PpTuFbFz: {
    // root type
    id6?: string | null // ID
  }
  PwzFJfRE: {
    // root type
    id90?: string | null // ID
  }
  QKdnhgbW: {
    // root type
    id3?: string | null // ID
  }
  QMkOOMdT: {
    // root type
    id122?: string | null // ID
  }
  QXSXwpMN: {
    // root type
    id211?: string | null // ID
  }
  QelISHAj: {
    // root type
    id58?: string | null // ID
  }
  QmPQoOZh: {
    // root type
    id220?: string | null // ID
  }
  Query: {}
  QxHzTNGy: {
    // root type
    id265?: string | null // ID
  }
  RCZmHSOp: {
    // root type
    id10?: string | null // ID
  }
  RMBiaCdu: {
    // root type
    id75?: string | null // ID
  }
  RNSfiIOi: {
    // root type
    id61?: string | null // ID
  }
  RTcWEgoC: {
    // root type
    id44?: string | null // ID
  }
  RVbkKVjJ: {
    // root type
    id231?: string | null // ID
  }
  RydRYmBj: {
    // root type
    id255?: string | null // ID
  }
  SBNNVkRr: {
    // root type
    id257?: string | null // ID
  }
  ShqdAPLQ: {
    // root type
    id297?: string | null // ID
  }
  SsKBGyvg: {
    // root type
    id50?: string | null // ID
  }
  Stydvxig: {
    // root type
    id245?: string | null // ID
  }
  TDURJGny: {
    // root type
    id2?: string | null // ID
  }
  TDztrYLm: {
    // root type
    id20?: string | null // ID
  }
  TKzetlpb: {
    // root type
    id171?: string | null // ID
  }
  TWLZYGzk: {
    // root type
    id59?: string | null // ID
  }
  TZHgNTAO: {
    // root type
    id215?: string | null // ID
  }
  TbgzaUgu: {
    // root type
    id123?: string | null // ID
  }
  TeZWMTzw: {
    // root type
    id175?: string | null // ID
  }
  TppFHtyg: {
    // root type
    id82?: string | null // ID
  }
  UGJqdGDT: {
    // root type
    id54?: string | null // ID
  }
  UuNFAnQg: {
    // root type
    id263?: string | null // ID
  }
  VAvPoGEb: {
    // root type
    id217?: string | null // ID
  }
  VynhbqCL: {
    // root type
    id26?: string | null // ID
  }
  WMsrUAGp: {
    // root type
    id181?: string | null // ID
  }
  WaVLDFqC: {
    // root type
    id136?: string | null // ID
  }
  WhUVndTD: {
    // root type
    id145?: string | null // ID
  }
  WoCNZkWp: {
    // root type
    id144?: string | null // ID
  }
  WsNuPHEi: {
    // root type
    id225?: string | null // ID
  }
  WsneBHrs: {
    // root type
    id101?: string | null // ID
  }
  WurxotQy: {
    // root type
    id72?: string | null // ID
  }
  XFYbFCkA: {
    // root type
    id69?: string | null // ID
  }
  XHvdKJbC: {
    // root type
    id285?: string | null // ID
  }
  XdzKjpVP: {
    // root type
    id4?: string | null // ID
  }
  Xqkpjqni: {
    // root type
    id15?: string | null // ID
  }
  XvyULguR: {
    // root type
    id104?: string | null // ID
  }
  XwweqpQZ: {
    // root type
    id275?: string | null // ID
  }
  YBZmfmWn: {
    // root type
    id88?: string | null // ID
  }
  YNnosqXJ: {
    // root type
    id244?: string | null // ID
  }
  YZpErVkH: {
    // root type
    id264?: string | null // ID
  }
  YwFARARB: {
    // root type
    id216?: string | null // ID
  }
  YxNVEAVR: {
    // root type
    id221?: string | null // ID
  }
  ZElcDXRS: {
    // root type
    id165?: string | null // ID
  }
  ZEyINaeG: {
    // root type
    id85?: string | null // ID
  }
  ZVaYkAdb: {
    // root type
    id279?: string | null // ID
  }
  ZbrxBPat: {
    // root type
    id232?: string | null // ID
  }
  ZeyczKBv: {
    // root type
    id12?: string | null // ID
  }
  ZrPlFevQ: {
    // root type
    id248?: string | null // ID
  }
  ZzRSmAyf: {
    // root type
    id161?: string | null // ID
  }
  aEOOAAKG: {
    // root type
    id166?: string | null // ID
  }
  aKYfIihK: {
    // root type
    id212?: string | null // ID
  }
  ahctkrlN: {
    // root type
    id222?: string | null // ID
  }
  arOfyZvi: {
    // root type
    id194?: string | null // ID
  }
  awDoUlrM: {
    // root type
    id119?: string | null // ID
  }
  bGRbQdGF: {
    // root type
    id143?: string | null // ID
  }
  bLcHZPpX: {
    // root type
    id230?: string | null // ID
  }
  bNaHPVhI: {
    // root type
    id234?: string | null // ID
  }
  bdmjhrZP: {
    // root type
    id36?: string | null // ID
  }
  bndWrLAg: {
    // root type
    id180?: string | null // ID
  }
  bpcReAKs: {
    // root type
    id48?: string | null // ID
  }
  bsuhpkhX: {
    // root type
    id67?: string | null // ID
  }
  cEORMlXC: {
    // root type
    id169?: string | null // ID
  }
  cGxDWUGD: {
    // root type
    id247?: string | null // ID
  }
  cMxjKIfV: {
    // root type
    id132?: string | null // ID
  }
  cXAmxvqv: {
    // root type
    id81?: string | null // ID
  }
  ctfzshTJ: {
    // root type
    id197?: string | null // ID
  }
  dAmPEeQn: {
    // root type
    id98?: string | null // ID
  }
  dHKrfYNo: {
    // root type
    id29?: string | null // ID
  }
  dOWdqEud: {
    // root type
    id66?: string | null // ID
  }
  dbFplbat: {
    // root type
    id184?: string | null // ID
  }
  deqJYjdv: {
    // root type
    id107?: string | null // ID
  }
  dnjGpfIS: {
    // root type
    id118?: string | null // ID
  }
  dnutiEie: {
    // root type
    id60?: string | null // ID
  }
  eJSSQaaC: {
    // root type
    id140?: string | null // ID
  }
  eROeesVg: {
    // root type
    id38?: string | null // ID
  }
  eWlLfMzi: {
    // root type
    id270?: string | null // ID
  }
  eemljdwg: {
    // root type
    id1?: string | null // ID
  }
  eggnlUYr: {
    // root type
    id109?: string | null // ID
  }
  euCWAGET: {
    // root type
    id158?: string | null // ID
  }
  fDAloqko: {
    // root type
    id16?: string | null // ID
  }
  fFyvwcxZ: {
    // root type
    id274?: string | null // ID
  }
  fPXYtcbT: {
    // root type
    id276?: string | null // ID
  }
  fXnweaVk: {
    // root type
    id52?: string | null // ID
  }
  faKaQEBn: {
    // root type
    id284?: string | null // ID
  }
  fvXQFkRb: {
    // root type
    id115?: string | null // ID
  }
  gQDQWruj: {
    // root type
    id22?: string | null // ID
  }
  gfyuMPLk: {
    // root type
    id189?: string | null // ID
  }
  gqhvwsiF: {
    // root type
    id23?: string | null // ID
  }
  gvxFkejN: {
    // root type
    id290?: string | null // ID
  }
  hAfKmdaD: {
    // root type
    id168?: string | null // ID
  }
  hBCadJbD: {
    // root type
    id138?: string | null // ID
  }
  hDsbddpo: {
    // root type
    id237?: string | null // ID
  }
  hEyyqHvv: {
    // root type
    id252?: string | null // ID
  }
  hIjYlIps: {
    // root type
    id210?: string | null // ID
  }
  hLptFSis: {
    // root type
    id91?: string | null // ID
  }
  hOqSbuBE: {
    // root type
    id27?: string | null // ID
  }
  hQiYNmDV: {
    // root type
    id127?: string | null // ID
  }
  hTNuohNQ: {
    // root type
    id271?: string | null // ID
  }
  hgsVEiUk: {
    // root type
    id240?: string | null // ID
  }
  hqweSGgf: {
    // root type
    id65?: string | null // ID
  }
  iVjcPoMw: {
    // root type
    id100?: string | null // ID
  }
  iWpPsvNV: {
    // root type
    id259?: string | null // ID
  }
  iZJAoMWm: {
    // root type
    id141?: string | null // ID
  }
  iqXgPwiC: {
    // root type
    id293?: string | null // ID
  }
  ixwjWVvf: {
    // root type
    id97?: string | null // ID
  }
  jAUaKDuu: {
    // root type
    id260?: string | null // ID
  }
  jCnSiJOq: {
    // root type
    id188?: string | null // ID
  }
  jciWswYD: {
    // root type
    id208?: string | null // ID
  }
  jkcwiNhe: {
    // root type
    id74?: string | null // ID
  }
  jmnxoYAy: {
    // root type
    id287?: string | null // ID
  }
  jnFMLyxL: {
    // root type
    id277?: string | null // ID
  }
  jrmLpsfT: {
    // root type
    id201?: string | null // ID
  }
  kAFbqgpE: {
    // root type
    id102?: string | null // ID
  }
  kAqRlGFR: {
    // root type
    id299?: string | null // ID
  }
  kEhnOaCH: {
    // root type
    id111?: string | null // ID
  }
  kHLLmfcE: {
    // root type
    id164?: string | null // ID
  }
  kKQNulhi: {
    // root type
    id5?: string | null // ID
  }
  kQUqAggO: {
    // root type
    id17?: string | null // ID
  }
  kXMItaoE: {
    // root type
    id154?: string | null // ID
  }
  kkQiMyOg: {
    // root type
    id33?: string | null // ID
  }
  klkPkaYU: {
    // root type
    id272?: string | null // ID
  }
  lFbOnWGE: {
    // root type
    id280?: string | null // ID
  }
  lPtHeBuR: {
    // root type
    id160?: string | null // ID
  }
  lVumUBIa: {
    // root type
    id174?: string | null // ID
  }
  laqqtHJN: {
    // root type
    id206?: string | null // ID
  }
  ldqzvWyd: {
    // root type
    id235?: string | null // ID
  }
  lhdysNNV: {
    // root type
    id71?: string | null // ID
  }
  lifwEmKz: {
    // root type
    id246?: string | null // ID
  }
  lsDifAmH: {
    // root type
    id298?: string | null // ID
  }
  mFSUfTPi: {
    // root type
    id116?: string | null // ID
  }
  mKbKQhyO: {
    // root type
    id167?: string | null // ID
  }
  mQIYoGzu: {
    // root type
    id28?: string | null // ID
  }
  mZmlDoBs: {
    // root type
    id273?: string | null // ID
  }
  mooFGlVS: {
    // root type
    id14?: string | null // ID
  }
  mtikMWMb: {
    // root type
    id261?: string | null // ID
  }
  muuoinyp: {
    // root type
    id70?: string | null // ID
  }
  newdlmuf: {
    // root type
    id39?: string | null // ID
  }
  oLLKSNvK: {
    // root type
    id176?: string | null // ID
  }
  ogOIrhgb: {
    // root type
    id47?: string | null // ID
  }
  phBMkPER: {
    // root type
    id236?: string | null // ID
  }
  pnfpWCgc: {
    // root type
    id99?: string | null // ID
  }
  ptQOpnjR: {
    // root type
    id190?: string | null // ID
  }
  qBIjdcrW: {
    // root type
    id142?: string | null // ID
  }
  qCzvlwRD: {
    // root type
    id80?: string | null // ID
  }
  qXlhbRwq: {
    // root type
    id78?: string | null // ID
  }
  rDLkvRXw: {
    // root type
    id296?: string | null // ID
  }
  rKZaCTrp: {
    // root type
    id89?: string | null // ID
  }
  rsrjXXbp: {
    // root type
    id267?: string | null // ID
  }
  sOPJOCHV: {
    // root type
    id108?: string | null // ID
  }
  sYmZSZhS: {
    // root type
    id45?: string | null // ID
  }
  tBRvILTt: {
    // root type
    id177?: string | null // ID
  }
  tHuINsQQ: {
    // root type
    id117?: string | null // ID
  }
  tWYLhGmP: {
    // root type
    id253?: string | null // ID
  }
  tfdcstkI: {
    // root type
    id262?: string | null // ID
  }
  tgBSTWuP: {
    // root type
    id40?: string | null // ID
  }
  tndtDdZP: {
    // root type
    id18?: string | null // ID
  }
  uaVbWYYy: {
    // root type
    id94?: string | null // ID
  }
  ubXmVvgH: {
    // root type
    id139?: string | null // ID
  }
  unjJMyow: {
    // root type
    id249?: string | null // ID
  }
  uqAoXisC: {
    // root type
    id9?: string | null // ID
  }
  uxqOEIwV: {
    // root type
    id49?: string | null // ID
  }
  vKNwRocJ: {
    // root type
    id229?: string | null // ID
  }
  vWCRSMfI: {
    // root type
    id37?: string | null // ID
  }
  vmWUXlxn: {
    // root type
    id233?: string | null // ID
  }
  vveXjotS: {
    // root type
    id11?: string | null // ID
  }
  wYUTmKCU: {
    // root type
    id291?: string | null // ID
  }
  wtjYwstX: {
    // root type
    id110?: string | null // ID
  }
  wvbxCjzQ: {
    // root type
    id131?: string | null // ID
  }
  xHmRwgeG: {
    // root type
    id42?: string | null // ID
  }
  xUqWuwDO: {
    // root type
    id288?: string | null // ID
  }
  xnxcQfWx: {
    // root type
    id76?: string | null // ID
  }
  yJNnsHEj: {
    // root type
    id135?: string | null // ID
  }
  yJubHpPP: {
    // root type
    id243?: string | null // ID
  }
  yMjEoECr: {
    // root type
    id196?: string | null // ID
  }
  yNNQUmqa: {
    // root type
    id150?: string | null // ID
  }
  yNumRBxd: {
    // root type
    id200?: string | null // ID
  }
  yPDuKVOh: {
    // root type
    id241?: string | null // ID
  }
  yrGYxJeE: {
    // root type
    id130?: string | null // ID
  }
  yvlysvTB: {
    // root type
    id269?: string | null // ID
  }
  zLwooCNa: {
    // root type
    id179?: string | null // ID
  }
  zUQFahzk: {
    // root type
    id283?: string | null // ID
  }
  zjnLruIQ: {
    // root type
    id289?: string | null // ID
  }
  zlPOFwWi: {
    // root type
    id183?: string | null // ID
  }
  zpZvbHAk: {
    // root type
    id124?: string | null // ID
  }
  zvGUhtyF: {
    // root type
    id186?: string | null // ID
  }
  BigUnion:
    | NexusGenRootTypes['aEOOAAKG']
    | NexusGenRootTypes['ahctkrlN']
    | NexusGenRootTypes['aKYfIihK']
    | NexusGenRootTypes['ALXAXBKq']
    | NexusGenRootTypes['AOogKhAD']
    | NexusGenRootTypes['ApAniugk']
    | NexusGenRootTypes['AQDzZPsI']
    | NexusGenRootTypes['arOfyZvi']
    | NexusGenRootTypes['AuMxHAoX']
    | NexusGenRootTypes['awDoUlrM']
    | NexusGenRootTypes['BAzfAeMR']
    | NexusGenRootTypes['bdmjhrZP']
    | NexusGenRootTypes['BFohGIGQ']
    | NexusGenRootTypes['bGRbQdGF']
    | NexusGenRootTypes['BiZjyuaY']
    | NexusGenRootTypes['Bjgguvhd']
    | NexusGenRootTypes['bLcHZPpX']
    | NexusGenRootTypes['bNaHPVhI']
    | NexusGenRootTypes['bndWrLAg']
    | NexusGenRootTypes['bpcReAKs']
    | NexusGenRootTypes['bsuhpkhX']
    | NexusGenRootTypes['BTIsXTrL']
    | NexusGenRootTypes['BWwxnXpM']
    | NexusGenRootTypes['BXowGvwZ']
    | NexusGenRootTypes['BYPWzETJ']
    | NexusGenRootTypes['CCXSFsMn']
    | NexusGenRootTypes['cEORMlXC']
    | NexusGenRootTypes['CgAQHanX']
    | NexusGenRootTypes['cGxDWUGD']
    | NexusGenRootTypes['cMxjKIfV']
    | NexusGenRootTypes['ctfzshTJ']
    | NexusGenRootTypes['cXAmxvqv']
    | NexusGenRootTypes['CXumheDD']
    | NexusGenRootTypes['dAmPEeQn']
    | NexusGenRootTypes['dbFplbat']
    | NexusGenRootTypes['DbgPTfDo']
    | NexusGenRootTypes['DBZLsxpr']
    | NexusGenRootTypes['deqJYjdv']
    | NexusGenRootTypes['DGxuhtpo']
    | NexusGenRootTypes['dHKrfYNo']
    | NexusGenRootTypes['DKEJFUiy']
    | NexusGenRootTypes['DkoAlvGn']
    | NexusGenRootTypes['DMggicLd']
    | NexusGenRootTypes['dnjGpfIS']
    | NexusGenRootTypes['DNohRdIN']
    | NexusGenRootTypes['dnutiEie']
    | NexusGenRootTypes['dOWdqEud']
    | NexusGenRootTypes['DpnWHIJW']
    | NexusGenRootTypes['ECChhDfK']
    | NexusGenRootTypes['eemljdwg']
    | NexusGenRootTypes['eggnlUYr']
    | NexusGenRootTypes['EhpNnQJw']
    | NexusGenRootTypes['EjIQIfmv']
    | NexusGenRootTypes['eJSSQaaC']
    | NexusGenRootTypes['EqEZXLCy']
    | NexusGenRootTypes['eROeesVg']
    | NexusGenRootTypes['EtPHwkkm']
    | NexusGenRootTypes['ETUiuOHD']
    | NexusGenRootTypes['euCWAGET']
    | NexusGenRootTypes['eWlLfMzi']
    | NexusGenRootTypes['EzcWBhIv']
    | NexusGenRootTypes['FaJAYKqm']
    | NexusGenRootTypes['faKaQEBn']
    | NexusGenRootTypes['FcFlCNAk']
    | NexusGenRootTypes['fDAloqko']
    | NexusGenRootTypes['FDouQoXO']
    | NexusGenRootTypes['fFyvwcxZ']
    | NexusGenRootTypes['FHLtgKoA']
    | NexusGenRootTypes['fPXYtcbT']
    | NexusGenRootTypes['FvftqquW']
    | NexusGenRootTypes['fvXQFkRb']
    | NexusGenRootTypes['fXnweaVk']
    | NexusGenRootTypes['GcpbGXTn']
    | NexusGenRootTypes['GDATeumz']
    | NexusGenRootTypes['GdxXCAak']
    | NexusGenRootTypes['gfyuMPLk']
    | NexusGenRootTypes['GhHKLcZe']
    | NexusGenRootTypes['gQDQWruj']
    | NexusGenRootTypes['gqhvwsiF']
    | NexusGenRootTypes['GsbHZkLK']
    | NexusGenRootTypes['gvxFkejN']
    | NexusGenRootTypes['GwkBnXKj']
    | NexusGenRootTypes['GYbaqoRT']
    | NexusGenRootTypes['GzglazdH']
    | NexusGenRootTypes['hAfKmdaD']
    | NexusGenRootTypes['hBCadJbD']
    | NexusGenRootTypes['HdiyXGxs']
    | NexusGenRootTypes['hDsbddpo']
    | NexusGenRootTypes['HENcJewx']
    | NexusGenRootTypes['hEyyqHvv']
    | NexusGenRootTypes['hgsVEiUk']
    | NexusGenRootTypes['HgYVPDgm']
    | NexusGenRootTypes['hIjYlIps']
    | NexusGenRootTypes['HIPZQFdS']
    | NexusGenRootTypes['HJmsvtgX']
    | NexusGenRootTypes['HjRDJhnX']
    | NexusGenRootTypes['hLptFSis']
    | NexusGenRootTypes['HLRWzsTU']
    | NexusGenRootTypes['HNLQTErw']
    | NexusGenRootTypes['hOqSbuBE']
    | NexusGenRootTypes['hQiYNmDV']
    | NexusGenRootTypes['hqweSGgf']
    | NexusGenRootTypes['hTNuohNQ']
    | NexusGenRootTypes['HwkXtjRP']
    | NexusGenRootTypes['HWMyawvm']
    | NexusGenRootTypes['HxCkBUxv']
    | NexusGenRootTypes['HXZUTyvG']
    | NexusGenRootTypes['HZbsVdoX']
    | NexusGenRootTypes['IAOEaBfb']
    | NexusGenRootTypes['IBZxPcZb']
    | NexusGenRootTypes['ICrkovFe']
    | NexusGenRootTypes['IGibGxHO']
    | NexusGenRootTypes['IhSGxaNc']
    | NexusGenRootTypes['IhtaZNUi']
    | NexusGenRootTypes['iqXgPwiC']
    | NexusGenRootTypes['IqZAiUKE']
    | NexusGenRootTypes['ISayJMYD']
    | NexusGenRootTypes['IuVQPFJN']
    | NexusGenRootTypes['iVjcPoMw']
    | NexusGenRootTypes['IWhegzTM']
    | NexusGenRootTypes['iWpPsvNV']
    | NexusGenRootTypes['ixwjWVvf']
    | NexusGenRootTypes['Iypygftg']
    | NexusGenRootTypes['IZERvBgk']
    | NexusGenRootTypes['iZJAoMWm']
    | NexusGenRootTypes['jAUaKDuu']
    | NexusGenRootTypes['JbsCxxcE']
    | NexusGenRootTypes['jciWswYD']
    | NexusGenRootTypes['jCnSiJOq']
    | NexusGenRootTypes['JjkgZKrV']
    | NexusGenRootTypes['jkcwiNhe']
    | NexusGenRootTypes['jmnxoYAy']
    | NexusGenRootTypes['jnFMLyxL']
    | NexusGenRootTypes['jrmLpsfT']
    | NexusGenRootTypes['JsAPYbRs']
    | NexusGenRootTypes['JuaucwDY']
    | NexusGenRootTypes['JXAbemqC']
    | NexusGenRootTypes['JZMQpjQv']
    | NexusGenRootTypes['kAFbqgpE']
    | NexusGenRootTypes['kAqRlGFR']
    | NexusGenRootTypes['KbTYPbTr']
    | NexusGenRootTypes['kEhnOaCH']
    | NexusGenRootTypes['KGbJMfhO']
    | NexusGenRootTypes['kHLLmfcE']
    | NexusGenRootTypes['kkQiMyOg']
    | NexusGenRootTypes['kKQNulhi']
    | NexusGenRootTypes['klkPkaYU']
    | NexusGenRootTypes['KoKtAqbt']
    | NexusGenRootTypes['kQUqAggO']
    | NexusGenRootTypes['KsPfaUFr']
    | NexusGenRootTypes['KvHHVcPa']
    | NexusGenRootTypes['KVIgujkc']
    | NexusGenRootTypes['kXMItaoE']
    | NexusGenRootTypes['laqqtHJN']
    | NexusGenRootTypes['LBePcCkW']
    | NexusGenRootTypes['ldqzvWyd']
    | NexusGenRootTypes['lFbOnWGE']
    | NexusGenRootTypes['lhdysNNV']
    | NexusGenRootTypes['LHxWkxKq']
    | NexusGenRootTypes['lifwEmKz']
    | NexusGenRootTypes['LMnZbpCI']
    | NexusGenRootTypes['lPtHeBuR']
    | NexusGenRootTypes['lsDifAmH']
    | NexusGenRootTypes['LtvKCzwe']
    | NexusGenRootTypes['lVumUBIa']
    | NexusGenRootTypes['mFSUfTPi']
    | NexusGenRootTypes['mKbKQhyO']
    | NexusGenRootTypes['mooFGlVS']
    | NexusGenRootTypes['MPQLFUho']
    | NexusGenRootTypes['mQIYoGzu']
    | NexusGenRootTypes['mtikMWMb']
    | NexusGenRootTypes['muuoinyp']
    | NexusGenRootTypes['MvpRfuhb']
    | NexusGenRootTypes['mZmlDoBs']
    | NexusGenRootTypes['NbTtwcUU']
    | NexusGenRootTypes['NczZcGdE']
    | NexusGenRootTypes['NefQmhqG']
    | NexusGenRootTypes['NETQHyFQ']
    | NexusGenRootTypes['newdlmuf']
    | NexusGenRootTypes['NlMnyCgu']
    | NexusGenRootTypes['NrrBYDim']
    | NexusGenRootTypes['NwPaWUGr']
    | NexusGenRootTypes['OBnGIgyZ']
    | NexusGenRootTypes['OehdOjXt']
    | NexusGenRootTypes['OfyEZrPd']
    | NexusGenRootTypes['ogOIrhgb']
    | NexusGenRootTypes['OjwpvBGH']
    | NexusGenRootTypes['oLLKSNvK']
    | NexusGenRootTypes['OwZeKGSU']
    | NexusGenRootTypes['OZfGULVa']
    | NexusGenRootTypes['PBGQfXYx']
    | NexusGenRootTypes['PGcwRfdb']
    | NexusGenRootTypes['phBMkPER']
    | NexusGenRootTypes['PHltFHbS']
    | NexusGenRootTypes['PNeiVzWR']
    | NexusGenRootTypes['pnfpWCgc']
    | NexusGenRootTypes['PNgZWWwo']
    | NexusGenRootTypes['PpTuFbFz']
    | NexusGenRootTypes['ptQOpnjR']
    | NexusGenRootTypes['PTtcHGFZ']
    | NexusGenRootTypes['PVCfSccj']
    | NexusGenRootTypes['PWOXDRzE']
    | NexusGenRootTypes['PwzFJfRE']
    | NexusGenRootTypes['PYCDIQQc']
    | NexusGenRootTypes['qBIjdcrW']
    | NexusGenRootTypes['qCzvlwRD']
    | NexusGenRootTypes['QelISHAj']
    | NexusGenRootTypes['QKdnhgbW']
    | NexusGenRootTypes['QMkOOMdT']
    | NexusGenRootTypes['QmPQoOZh']
    | NexusGenRootTypes['QxHzTNGy']
    | NexusGenRootTypes['qXlhbRwq']
    | NexusGenRootTypes['QXSXwpMN']
    | NexusGenRootTypes['RCZmHSOp']
    | NexusGenRootTypes['rDLkvRXw']
    | NexusGenRootTypes['rKZaCTrp']
    | NexusGenRootTypes['RMBiaCdu']
    | NexusGenRootTypes['RNSfiIOi']
    | NexusGenRootTypes['rsrjXXbp']
    | NexusGenRootTypes['RTcWEgoC']
    | NexusGenRootTypes['RVbkKVjJ']
    | NexusGenRootTypes['RydRYmBj']
    | NexusGenRootTypes['SBNNVkRr']
    | NexusGenRootTypes['ShqdAPLQ']
    | NexusGenRootTypes['sOPJOCHV']
    | NexusGenRootTypes['SsKBGyvg']
    | NexusGenRootTypes['Stydvxig']
    | NexusGenRootTypes['sYmZSZhS']
    | NexusGenRootTypes['TbgzaUgu']
    | NexusGenRootTypes['tBRvILTt']
    | NexusGenRootTypes['TDURJGny']
    | NexusGenRootTypes['TDztrYLm']
    | NexusGenRootTypes['TeZWMTzw']
    | NexusGenRootTypes['tfdcstkI']
    | NexusGenRootTypes['tgBSTWuP']
    | NexusGenRootTypes['tHuINsQQ']
    | NexusGenRootTypes['TKzetlpb']
    | NexusGenRootTypes['tndtDdZP']
    | NexusGenRootTypes['TppFHtyg']
    | NexusGenRootTypes['TWLZYGzk']
    | NexusGenRootTypes['tWYLhGmP']
    | NexusGenRootTypes['TZHgNTAO']
    | NexusGenRootTypes['uaVbWYYy']
    | NexusGenRootTypes['ubXmVvgH']
    | NexusGenRootTypes['UGJqdGDT']
    | NexusGenRootTypes['unjJMyow']
    | NexusGenRootTypes['uqAoXisC']
    | NexusGenRootTypes['UuNFAnQg']
    | NexusGenRootTypes['uxqOEIwV']
    | NexusGenRootTypes['VAvPoGEb']
    | NexusGenRootTypes['vKNwRocJ']
    | NexusGenRootTypes['vmWUXlxn']
    | NexusGenRootTypes['vveXjotS']
    | NexusGenRootTypes['vWCRSMfI']
    | NexusGenRootTypes['VynhbqCL']
    | NexusGenRootTypes['WaVLDFqC']
    | NexusGenRootTypes['WhUVndTD']
    | NexusGenRootTypes['WMsrUAGp']
    | NexusGenRootTypes['WoCNZkWp']
    | NexusGenRootTypes['WsneBHrs']
    | NexusGenRootTypes['WsNuPHEi']
    | NexusGenRootTypes['wtjYwstX']
    | NexusGenRootTypes['WurxotQy']
    | NexusGenRootTypes['wvbxCjzQ']
    | NexusGenRootTypes['wYUTmKCU']
    | NexusGenRootTypes['XdzKjpVP']
    | NexusGenRootTypes['XFYbFCkA']
    | NexusGenRootTypes['xHmRwgeG']
    | NexusGenRootTypes['XHvdKJbC']
    | NexusGenRootTypes['xnxcQfWx']
    | NexusGenRootTypes['Xqkpjqni']
    | NexusGenRootTypes['xUqWuwDO']
    | NexusGenRootTypes['XvyULguR']
    | NexusGenRootTypes['XwweqpQZ']
    | NexusGenRootTypes['YBZmfmWn']
    | NexusGenRootTypes['yJNnsHEj']
    | NexusGenRootTypes['yJubHpPP']
    | NexusGenRootTypes['yMjEoECr']
    | NexusGenRootTypes['YNnosqXJ']
    | NexusGenRootTypes['yNNQUmqa']
    | NexusGenRootTypes['yNumRBxd']
    | NexusGenRootTypes['yPDuKVOh']
    | NexusGenRootTypes['yrGYxJeE']
    | NexusGenRootTypes['yvlysvTB']
    | NexusGenRootTypes['YwFARARB']
    | NexusGenRootTypes['YxNVEAVR']
    | NexusGenRootTypes['YZpErVkH']
    | NexusGenRootTypes['ZbrxBPat']
    | NexusGenRootTypes['ZElcDXRS']
    | NexusGenRootTypes['ZeyczKBv']
    | NexusGenRootTypes['ZEyINaeG']
    | NexusGenRootTypes['zjnLruIQ']
    | NexusGenRootTypes['zlPOFwWi']
    | NexusGenRootTypes['zLwooCNa']
    | NexusGenRootTypes['zpZvbHAk']
    | NexusGenRootTypes['ZrPlFevQ']
    | NexusGenRootTypes['zUQFahzk']
    | NexusGenRootTypes['ZVaYkAdb']
    | NexusGenRootTypes['zvGUhtyF']
    | NexusGenRootTypes['ZzRSmAyf']
  MediumUnionType:
    | NexusGenRootTypes['AOogKhAD']
    | NexusGenRootTypes['ApAniugk']
    | NexusGenRootTypes['AuMxHAoX']
    | NexusGenRootTypes['awDoUlrM']
    | NexusGenRootTypes['bGRbQdGF']
    | NexusGenRootTypes['bsuhpkhX']
    | NexusGenRootTypes['BXowGvwZ']
    | NexusGenRootTypes['CgAQHanX']
    | NexusGenRootTypes['cMxjKIfV']
    | NexusGenRootTypes['cXAmxvqv']
    | NexusGenRootTypes['dAmPEeQn']
    | NexusGenRootTypes['DBZLsxpr']
    | NexusGenRootTypes['deqJYjdv']
    | NexusGenRootTypes['dnjGpfIS']
    | NexusGenRootTypes['dnutiEie']
    | NexusGenRootTypes['dOWdqEud']
    | NexusGenRootTypes['ECChhDfK']
    | NexusGenRootTypes['eggnlUYr']
    | NexusGenRootTypes['EhpNnQJw']
    | NexusGenRootTypes['EjIQIfmv']
    | NexusGenRootTypes['eJSSQaaC']
    | NexusGenRootTypes['EtPHwkkm']
    | NexusGenRootTypes['FaJAYKqm']
    | NexusGenRootTypes['fvXQFkRb']
    | NexusGenRootTypes['fXnweaVk']
    | NexusGenRootTypes['GYbaqoRT']
    | NexusGenRootTypes['GzglazdH']
    | NexusGenRootTypes['hBCadJbD']
    | NexusGenRootTypes['HgYVPDgm']
    | NexusGenRootTypes['HjRDJhnX']
    | NexusGenRootTypes['hLptFSis']
    | NexusGenRootTypes['hQiYNmDV']
    | NexusGenRootTypes['hqweSGgf']
    | NexusGenRootTypes['HwkXtjRP']
    | NexusGenRootTypes['HZbsVdoX']
    | NexusGenRootTypes['IAOEaBfb']
    | NexusGenRootTypes['ICrkovFe']
    | NexusGenRootTypes['IhSGxaNc']
    | NexusGenRootTypes['ISayJMYD']
    | NexusGenRootTypes['iVjcPoMw']
    | NexusGenRootTypes['ixwjWVvf']
    | NexusGenRootTypes['Iypygftg']
    | NexusGenRootTypes['iZJAoMWm']
    | NexusGenRootTypes['jkcwiNhe']
    | NexusGenRootTypes['JuaucwDY']
    | NexusGenRootTypes['JZMQpjQv']
    | NexusGenRootTypes['kAFbqgpE']
    | NexusGenRootTypes['KbTYPbTr']
    | NexusGenRootTypes['kEhnOaCH']
    | NexusGenRootTypes['KsPfaUFr']
    | NexusGenRootTypes['KvHHVcPa']
    | NexusGenRootTypes['LBePcCkW']
    | NexusGenRootTypes['lhdysNNV']
    | NexusGenRootTypes['LHxWkxKq']
    | NexusGenRootTypes['LMnZbpCI']
    | NexusGenRootTypes['mFSUfTPi']
    | NexusGenRootTypes['muuoinyp']
    | NexusGenRootTypes['NefQmhqG']
    | NexusGenRootTypes['NETQHyFQ']
    | NexusGenRootTypes['OwZeKGSU']
    | NexusGenRootTypes['PBGQfXYx']
    | NexusGenRootTypes['PGcwRfdb']
    | NexusGenRootTypes['PNeiVzWR']
    | NexusGenRootTypes['pnfpWCgc']
    | NexusGenRootTypes['PNgZWWwo']
    | NexusGenRootTypes['PTtcHGFZ']
    | NexusGenRootTypes['PWOXDRzE']
    | NexusGenRootTypes['PwzFJfRE']
    | NexusGenRootTypes['qBIjdcrW']
    | NexusGenRootTypes['qCzvlwRD']
    | NexusGenRootTypes['QelISHAj']
    | NexusGenRootTypes['QMkOOMdT']
    | NexusGenRootTypes['qXlhbRwq']
    | NexusGenRootTypes['rKZaCTrp']
    | NexusGenRootTypes['RMBiaCdu']
    | NexusGenRootTypes['RNSfiIOi']
    | NexusGenRootTypes['sOPJOCHV']
    | NexusGenRootTypes['SsKBGyvg']
    | NexusGenRootTypes['TbgzaUgu']
    | NexusGenRootTypes['tHuINsQQ']
    | NexusGenRootTypes['TppFHtyg']
    | NexusGenRootTypes['TWLZYGzk']
    | NexusGenRootTypes['uaVbWYYy']
    | NexusGenRootTypes['ubXmVvgH']
    | NexusGenRootTypes['UGJqdGDT']
    | NexusGenRootTypes['WaVLDFqC']
    | NexusGenRootTypes['WhUVndTD']
    | NexusGenRootTypes['WoCNZkWp']
    | NexusGenRootTypes['WsneBHrs']
    | NexusGenRootTypes['wtjYwstX']
    | NexusGenRootTypes['WurxotQy']
    | NexusGenRootTypes['wvbxCjzQ']
    | NexusGenRootTypes['XFYbFCkA']
    | NexusGenRootTypes['xnxcQfWx']
    | NexusGenRootTypes['XvyULguR']
    | NexusGenRootTypes['YBZmfmWn']
    | NexusGenRootTypes['yJNnsHEj']
    | NexusGenRootTypes['yrGYxJeE']
    | NexusGenRootTypes['ZEyINaeG']
    | NexusGenRootTypes['zpZvbHAk']
  MediumUnionTypes:
    | NexusGenRootTypes['ALXAXBKq']
    | NexusGenRootTypes['AOogKhAD']
    | NexusGenRootTypes['ApAniugk']
    | NexusGenRootTypes['bdmjhrZP']
    | NexusGenRootTypes['BiZjyuaY']
    | NexusGenRootTypes['bpcReAKs']
    | NexusGenRootTypes['bsuhpkhX']
    | NexusGenRootTypes['BXowGvwZ']
    | NexusGenRootTypes['CgAQHanX']
    | NexusGenRootTypes['cXAmxvqv']
    | NexusGenRootTypes['dAmPEeQn']
    | NexusGenRootTypes['dHKrfYNo']
    | NexusGenRootTypes['dnutiEie']
    | NexusGenRootTypes['dOWdqEud']
    | NexusGenRootTypes['DpnWHIJW']
    | NexusGenRootTypes['ECChhDfK']
    | NexusGenRootTypes['eemljdwg']
    | NexusGenRootTypes['EqEZXLCy']
    | NexusGenRootTypes['eROeesVg']
    | NexusGenRootTypes['EtPHwkkm']
    | NexusGenRootTypes['ETUiuOHD']
    | NexusGenRootTypes['FaJAYKqm']
    | NexusGenRootTypes['fDAloqko']
    | NexusGenRootTypes['fXnweaVk']
    | NexusGenRootTypes['GdxXCAak']
    | NexusGenRootTypes['gQDQWruj']
    | NexusGenRootTypes['gqhvwsiF']
    | NexusGenRootTypes['GsbHZkLK']
    | NexusGenRootTypes['GzglazdH']
    | NexusGenRootTypes['HgYVPDgm']
    | NexusGenRootTypes['hLptFSis']
    | NexusGenRootTypes['hOqSbuBE']
    | NexusGenRootTypes['hqweSGgf']
    | NexusGenRootTypes['HwkXtjRP']
    | NexusGenRootTypes['HXZUTyvG']
    | NexusGenRootTypes['HZbsVdoX']
    | NexusGenRootTypes['ICrkovFe']
    | NexusGenRootTypes['IWhegzTM']
    | NexusGenRootTypes['ixwjWVvf']
    | NexusGenRootTypes['Iypygftg']
    | NexusGenRootTypes['IZERvBgk']
    | NexusGenRootTypes['JbsCxxcE']
    | NexusGenRootTypes['jkcwiNhe']
    | NexusGenRootTypes['KbTYPbTr']
    | NexusGenRootTypes['kkQiMyOg']
    | NexusGenRootTypes['kKQNulhi']
    | NexusGenRootTypes['kQUqAggO']
    | NexusGenRootTypes['KsPfaUFr']
    | NexusGenRootTypes['lhdysNNV']
    | NexusGenRootTypes['LHxWkxKq']
    | NexusGenRootTypes['LtvKCzwe']
    | NexusGenRootTypes['mooFGlVS']
    | NexusGenRootTypes['MPQLFUho']
    | NexusGenRootTypes['mQIYoGzu']
    | NexusGenRootTypes['muuoinyp']
    | NexusGenRootTypes['NbTtwcUU']
    | NexusGenRootTypes['NETQHyFQ']
    | NexusGenRootTypes['newdlmuf']
    | NexusGenRootTypes['OfyEZrPd']
    | NexusGenRootTypes['ogOIrhgb']
    | NexusGenRootTypes['PBGQfXYx']
    | NexusGenRootTypes['PGcwRfdb']
    | NexusGenRootTypes['pnfpWCgc']
    | NexusGenRootTypes['PpTuFbFz']
    | NexusGenRootTypes['PWOXDRzE']
    | NexusGenRootTypes['PwzFJfRE']
    | NexusGenRootTypes['PYCDIQQc']
    | NexusGenRootTypes['qCzvlwRD']
    | NexusGenRootTypes['QelISHAj']
    | NexusGenRootTypes['QKdnhgbW']
    | NexusGenRootTypes['qXlhbRwq']
    | NexusGenRootTypes['RCZmHSOp']
    | NexusGenRootTypes['rKZaCTrp']
    | NexusGenRootTypes['RMBiaCdu']
    | NexusGenRootTypes['RNSfiIOi']
    | NexusGenRootTypes['RTcWEgoC']
    | NexusGenRootTypes['SsKBGyvg']
    | NexusGenRootTypes['sYmZSZhS']
    | NexusGenRootTypes['TDURJGny']
    | NexusGenRootTypes['TDztrYLm']
    | NexusGenRootTypes['tgBSTWuP']
    | NexusGenRootTypes['tndtDdZP']
    | NexusGenRootTypes['TppFHtyg']
    | NexusGenRootTypes['TWLZYGzk']
    | NexusGenRootTypes['uaVbWYYy']
    | NexusGenRootTypes['UGJqdGDT']
    | NexusGenRootTypes['uqAoXisC']
    | NexusGenRootTypes['uxqOEIwV']
    | NexusGenRootTypes['vveXjotS']
    | NexusGenRootTypes['vWCRSMfI']
    | NexusGenRootTypes['VynhbqCL']
    | NexusGenRootTypes['WurxotQy']
    | NexusGenRootTypes['XdzKjpVP']
    | NexusGenRootTypes['XFYbFCkA']
    | NexusGenRootTypes['xHmRwgeG']
    | NexusGenRootTypes['xnxcQfWx']
    | NexusGenRootTypes['Xqkpjqni']
    | NexusGenRootTypes['YBZmfmWn']
    | NexusGenRootTypes['ZeyczKBv']
    | NexusGenRootTypes['ZEyINaeG']
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  String: NexusGenScalars['String']
  Int: NexusGenScalars['Int']
  Float: NexusGenScalars['Float']
  Boolean: NexusGenScalars['Boolean']
  ID: NexusGenScalars['ID']
}

export interface NexusGenFieldTypes {
  ALXAXBKq: {
    // field return type
    id41: string | null // ID
  }
  AOogKhAD: {
    // field return type
    id53: string | null // ID
  }
  AQDzZPsI: {
    // field return type
    id193: string | null // ID
  }
  ApAniugk: {
    // field return type
    id51: string | null // ID
  }
  AuMxHAoX: {
    // field return type
    id146: string | null // ID
  }
  BAzfAeMR: {
    // field return type
    id191: string | null // ID
  }
  BFohGIGQ: {
    // field return type
    id286: string | null // ID
  }
  BTIsXTrL: {
    // field return type
    id250: string | null // ID
  }
  BWwxnXpM: {
    // field return type
    id294: string | null // ID
  }
  BXowGvwZ: {
    // field return type
    id63: string | null // ID
  }
  BYPWzETJ: {
    // field return type
    id266: string | null // ID
  }
  BiZjyuaY: {
    // field return type
    id25: string | null // ID
  }
  Bjgguvhd: {
    // field return type
    id170: string | null // ID
  }
  CCXSFsMn: {
    // field return type
    id268: string | null // ID
  }
  CXumheDD: {
    // field return type
    id172: string | null // ID
  }
  CgAQHanX: {
    // field return type
    id96: string | null // ID
  }
  DBZLsxpr: {
    // field return type
    id137: string | null // ID
  }
  DGxuhtpo: {
    // field return type
    id219: string | null // ID
  }
  DKEJFUiy: {
    // field return type
    id295: string | null // ID
  }
  DMggicLd: {
    // field return type
    id239: string | null // ID
  }
  DNohRdIN: {
    // field return type
    id203: string | null // ID
  }
  DbgPTfDo: {
    // field return type
    id254: string | null // ID
  }
  DkoAlvGn: {
    // field return type
    id282: string | null // ID
  }
  DpnWHIJW: {
    // field return type
    id7: string | null // ID
  }
  ECChhDfK: {
    // field return type
    id79: string | null // ID
  }
  ETUiuOHD: {
    // field return type
    id35: string | null // ID
  }
  EhpNnQJw: {
    // field return type
    id121: string | null // ID
  }
  EjIQIfmv: {
    // field return type
    id126: string | null // ID
  }
  EqEZXLCy: {
    // field return type
    id30: string | null // ID
  }
  EtPHwkkm: {
    // field return type
    id57: string | null // ID
  }
  EzcWBhIv: {
    // field return type
    id214: string | null // ID
  }
  FDouQoXO: {
    // field return type
    id173: string | null // ID
  }
  FHLtgKoA: {
    // field return type
    id258: string | null // ID
  }
  FaJAYKqm: {
    // field return type
    id93: string | null // ID
  }
  FcFlCNAk: {
    // field return type
    id228: string | null // ID
  }
  FvftqquW: {
    // field return type
    id281: string | null // ID
  }
  GDATeumz: {
    // field return type
    id256: string | null // ID
  }
  GYbaqoRT: {
    // field return type
    id105: string | null // ID
  }
  GcpbGXTn: {
    // field return type
    id218: string | null // ID
  }
  GdxXCAak: {
    // field return type
    id13: string | null // ID
  }
  GhHKLcZe: {
    // field return type
    id199: string | null // ID
  }
  GsbHZkLK: {
    // field return type
    id34: string | null // ID
  }
  GwkBnXKj: {
    // field return type
    id207: string | null // ID
  }
  GzglazdH: {
    // field return type
    id95: string | null // ID
  }
  HENcJewx: {
    // field return type
    id185: string | null // ID
  }
  HIPZQFdS: {
    // field return type
    id251: string | null // ID
  }
  HJmsvtgX: {
    // field return type
    id151: string | null // ID
  }
  HLRWzsTU: {
    // field return type
    id182: string | null // ID
  }
  HNLQTErw: {
    // field return type
    id155: string | null // ID
  }
  HWMyawvm: {
    // field return type
    id187: string | null // ID
  }
  HXZUTyvG: {
    // field return type
    id46: string | null // ID
  }
  HZbsVdoX: {
    // field return type
    id68: string | null // ID
  }
  HdiyXGxs: {
    // field return type
    id178: string | null // ID
  }
  HgYVPDgm: {
    // field return type
    id87: string | null // ID
  }
  HjRDJhnX: {
    // field return type
    id133: string | null // ID
  }
  HwkXtjRP: {
    // field return type
    id84: string | null // ID
  }
  HxCkBUxv: {
    // field return type
    id192: string | null // ID
  }
  IAOEaBfb: {
    // field return type
    id120: string | null // ID
  }
  IBZxPcZb: {
    // field return type
    id205: string | null // ID
  }
  ICrkovFe: {
    // field return type
    id73: string | null // ID
  }
  IGibGxHO: {
    // field return type
    id204: string | null // ID
  }
  ISayJMYD: {
    // field return type
    id129: string | null // ID
  }
  IWhegzTM: {
    // field return type
    id43: string | null // ID
  }
  IZERvBgk: {
    // field return type
    id32: string | null // ID
  }
  IhSGxaNc: {
    // field return type
    id103: string | null // ID
  }
  IhtaZNUi: {
    // field return type
    id238: string | null // ID
  }
  IqZAiUKE: {
    // field return type
    id223: string | null // ID
  }
  IuVQPFJN: {
    // field return type
    id152: string | null // ID
  }
  Iypygftg: {
    // field return type
    id77: string | null // ID
  }
  JXAbemqC: {
    // field return type
    id153: string | null // ID
  }
  JZMQpjQv: {
    // field return type
    id125: string | null // ID
  }
  JbsCxxcE: {
    // field return type
    id8: string | null // ID
  }
  JjkgZKrV: {
    // field return type
    id202: string | null // ID
  }
  JsAPYbRs: {
    // field return type
    id156: string | null // ID
  }
  JuaucwDY: {
    // field return type
    id134: string | null // ID
  }
  KGbJMfhO: {
    // field return type
    id159: string | null // ID
  }
  KVIgujkc: {
    // field return type
    id157: string | null // ID
  }
  KbTYPbTr: {
    // field return type
    id92: string | null // ID
  }
  KoKtAqbt: {
    // field return type
    id213: string | null // ID
  }
  KsPfaUFr: {
    // field return type
    id86: string | null // ID
  }
  KvHHVcPa: {
    // field return type
    id147: string | null // ID
  }
  LBePcCkW: {
    // field return type
    id112: string | null // ID
  }
  LHxWkxKq: {
    // field return type
    id64: string | null // ID
  }
  LMnZbpCI: {
    // field return type
    id106: string | null // ID
  }
  LtvKCzwe: {
    // field return type
    id19: string | null // ID
  }
  MPQLFUho: {
    // field return type
    id31: string | null // ID
  }
  MvpRfuhb: {
    // field return type
    id198: string | null // ID
  }
  NETQHyFQ: {
    // field return type
    id55: string | null // ID
  }
  NbTtwcUU: {
    // field return type
    id0: string | null // ID
  }
  NczZcGdE: {
    // field return type
    id209: string | null // ID
  }
  NefQmhqG: {
    // field return type
    id149: string | null // ID
  }
  NlMnyCgu: {
    // field return type
    id162: string | null // ID
  }
  NrrBYDim: {
    // field return type
    id163: string | null // ID
  }
  NwPaWUGr: {
    // field return type
    id292: string | null // ID
  }
  OBnGIgyZ: {
    // field return type
    id242: string | null // ID
  }
  OZfGULVa: {
    // field return type
    id195: string | null // ID
  }
  OehdOjXt: {
    // field return type
    id278: string | null // ID
  }
  OfyEZrPd: {
    // field return type
    id21: string | null // ID
  }
  OjwpvBGH: {
    // field return type
    id227: string | null // ID
  }
  OwZeKGSU: {
    // field return type
    id128: string | null // ID
  }
  PBGQfXYx: {
    // field return type
    id83: string | null // ID
  }
  PGcwRfdb: {
    // field return type
    id62: string | null // ID
  }
  PHltFHbS: {
    // field return type
    id226: string | null // ID
  }
  PNeiVzWR: {
    // field return type
    id113: string | null // ID
  }
  PNgZWWwo: {
    // field return type
    id148: string | null // ID
  }
  PTtcHGFZ: {
    // field return type
    id114: string | null // ID
  }
  PVCfSccj: {
    // field return type
    id224: string | null // ID
  }
  PWOXDRzE: {
    // field return type
    id56: string | null // ID
  }
  PYCDIQQc: {
    // field return type
    id24: string | null // ID
  }
  PpTuFbFz: {
    // field return type
    id6: string | null // ID
  }
  PwzFJfRE: {
    // field return type
    id90: string | null // ID
  }
  QKdnhgbW: {
    // field return type
    id3: string | null // ID
  }
  QMkOOMdT: {
    // field return type
    id122: string | null // ID
  }
  QXSXwpMN: {
    // field return type
    id211: string | null // ID
  }
  QelISHAj: {
    // field return type
    id58: string | null // ID
  }
  QmPQoOZh: {
    // field return type
    id220: string | null // ID
  }
  Query: {
    // field return type
    ok: boolean // Boolean!
  }
  QxHzTNGy: {
    // field return type
    id265: string | null // ID
  }
  RCZmHSOp: {
    // field return type
    id10: string | null // ID
  }
  RMBiaCdu: {
    // field return type
    id75: string | null // ID
  }
  RNSfiIOi: {
    // field return type
    id61: string | null // ID
  }
  RTcWEgoC: {
    // field return type
    id44: string | null // ID
  }
  RVbkKVjJ: {
    // field return type
    id231: string | null // ID
  }
  RydRYmBj: {
    // field return type
    id255: string | null // ID
  }
  SBNNVkRr: {
    // field return type
    id257: string | null // ID
  }
  ShqdAPLQ: {
    // field return type
    id297: string | null // ID
  }
  SsKBGyvg: {
    // field return type
    id50: string | null // ID
  }
  Stydvxig: {
    // field return type
    id245: string | null // ID
  }
  TDURJGny: {
    // field return type
    id2: string | null // ID
  }
  TDztrYLm: {
    // field return type
    id20: string | null // ID
  }
  TKzetlpb: {
    // field return type
    id171: string | null // ID
  }
  TWLZYGzk: {
    // field return type
    id59: string | null // ID
  }
  TZHgNTAO: {
    // field return type
    id215: string | null // ID
  }
  TbgzaUgu: {
    // field return type
    id123: string | null // ID
  }
  TeZWMTzw: {
    // field return type
    id175: string | null // ID
  }
  TppFHtyg: {
    // field return type
    id82: string | null // ID
  }
  UGJqdGDT: {
    // field return type
    id54: string | null // ID
  }
  UuNFAnQg: {
    // field return type
    id263: string | null // ID
  }
  VAvPoGEb: {
    // field return type
    id217: string | null // ID
  }
  VynhbqCL: {
    // field return type
    id26: string | null // ID
  }
  WMsrUAGp: {
    // field return type
    id181: string | null // ID
  }
  WaVLDFqC: {
    // field return type
    id136: string | null // ID
  }
  WhUVndTD: {
    // field return type
    id145: string | null // ID
  }
  WoCNZkWp: {
    // field return type
    id144: string | null // ID
  }
  WsNuPHEi: {
    // field return type
    id225: string | null // ID
  }
  WsneBHrs: {
    // field return type
    id101: string | null // ID
  }
  WurxotQy: {
    // field return type
    id72: string | null // ID
  }
  XFYbFCkA: {
    // field return type
    id69: string | null // ID
  }
  XHvdKJbC: {
    // field return type
    id285: string | null // ID
  }
  XdzKjpVP: {
    // field return type
    id4: string | null // ID
  }
  Xqkpjqni: {
    // field return type
    id15: string | null // ID
  }
  XvyULguR: {
    // field return type
    id104: string | null // ID
  }
  XwweqpQZ: {
    // field return type
    id275: string | null // ID
  }
  YBZmfmWn: {
    // field return type
    id88: string | null // ID
  }
  YNnosqXJ: {
    // field return type
    id244: string | null // ID
  }
  YZpErVkH: {
    // field return type
    id264: string | null // ID
  }
  YwFARARB: {
    // field return type
    id216: string | null // ID
  }
  YxNVEAVR: {
    // field return type
    id221: string | null // ID
  }
  ZElcDXRS: {
    // field return type
    id165: string | null // ID
  }
  ZEyINaeG: {
    // field return type
    id85: string | null // ID
  }
  ZVaYkAdb: {
    // field return type
    id279: string | null // ID
  }
  ZbrxBPat: {
    // field return type
    id232: string | null // ID
  }
  ZeyczKBv: {
    // field return type
    id12: string | null // ID
  }
  ZrPlFevQ: {
    // field return type
    id248: string | null // ID
  }
  ZzRSmAyf: {
    // field return type
    id161: string | null // ID
  }
  aEOOAAKG: {
    // field return type
    id166: string | null // ID
  }
  aKYfIihK: {
    // field return type
    id212: string | null // ID
  }
  ahctkrlN: {
    // field return type
    id222: string | null // ID
  }
  arOfyZvi: {
    // field return type
    id194: string | null // ID
  }
  awDoUlrM: {
    // field return type
    id119: string | null // ID
  }
  bGRbQdGF: {
    // field return type
    id143: string | null // ID
  }
  bLcHZPpX: {
    // field return type
    id230: string | null // ID
  }
  bNaHPVhI: {
    // field return type
    id234: string | null // ID
  }
  bdmjhrZP: {
    // field return type
    id36: string | null // ID
  }
  bndWrLAg: {
    // field return type
    id180: string | null // ID
  }
  bpcReAKs: {
    // field return type
    id48: string | null // ID
  }
  bsuhpkhX: {
    // field return type
    id67: string | null // ID
  }
  cEORMlXC: {
    // field return type
    id169: string | null // ID
  }
  cGxDWUGD: {
    // field return type
    id247: string | null // ID
  }
  cMxjKIfV: {
    // field return type
    id132: string | null // ID
  }
  cXAmxvqv: {
    // field return type
    id81: string | null // ID
  }
  ctfzshTJ: {
    // field return type
    id197: string | null // ID
  }
  dAmPEeQn: {
    // field return type
    id98: string | null // ID
  }
  dHKrfYNo: {
    // field return type
    id29: string | null // ID
  }
  dOWdqEud: {
    // field return type
    id66: string | null // ID
  }
  dbFplbat: {
    // field return type
    id184: string | null // ID
  }
  deqJYjdv: {
    // field return type
    id107: string | null // ID
  }
  dnjGpfIS: {
    // field return type
    id118: string | null // ID
  }
  dnutiEie: {
    // field return type
    id60: string | null // ID
  }
  eJSSQaaC: {
    // field return type
    id140: string | null // ID
  }
  eROeesVg: {
    // field return type
    id38: string | null // ID
  }
  eWlLfMzi: {
    // field return type
    id270: string | null // ID
  }
  eemljdwg: {
    // field return type
    id1: string | null // ID
  }
  eggnlUYr: {
    // field return type
    id109: string | null // ID
  }
  euCWAGET: {
    // field return type
    id158: string | null // ID
  }
  fDAloqko: {
    // field return type
    id16: string | null // ID
  }
  fFyvwcxZ: {
    // field return type
    id274: string | null // ID
  }
  fPXYtcbT: {
    // field return type
    id276: string | null // ID
  }
  fXnweaVk: {
    // field return type
    id52: string | null // ID
  }
  faKaQEBn: {
    // field return type
    id284: string | null // ID
  }
  fvXQFkRb: {
    // field return type
    id115: string | null // ID
  }
  gQDQWruj: {
    // field return type
    id22: string | null // ID
  }
  gfyuMPLk: {
    // field return type
    id189: string | null // ID
  }
  gqhvwsiF: {
    // field return type
    id23: string | null // ID
  }
  gvxFkejN: {
    // field return type
    id290: string | null // ID
  }
  hAfKmdaD: {
    // field return type
    id168: string | null // ID
  }
  hBCadJbD: {
    // field return type
    id138: string | null // ID
  }
  hDsbddpo: {
    // field return type
    id237: string | null // ID
  }
  hEyyqHvv: {
    // field return type
    id252: string | null // ID
  }
  hIjYlIps: {
    // field return type
    id210: string | null // ID
  }
  hLptFSis: {
    // field return type
    id91: string | null // ID
  }
  hOqSbuBE: {
    // field return type
    id27: string | null // ID
  }
  hQiYNmDV: {
    // field return type
    id127: string | null // ID
  }
  hTNuohNQ: {
    // field return type
    id271: string | null // ID
  }
  hgsVEiUk: {
    // field return type
    id240: string | null // ID
  }
  hqweSGgf: {
    // field return type
    id65: string | null // ID
  }
  iVjcPoMw: {
    // field return type
    id100: string | null // ID
  }
  iWpPsvNV: {
    // field return type
    id259: string | null // ID
  }
  iZJAoMWm: {
    // field return type
    id141: string | null // ID
  }
  iqXgPwiC: {
    // field return type
    id293: string | null // ID
  }
  ixwjWVvf: {
    // field return type
    id97: string | null // ID
  }
  jAUaKDuu: {
    // field return type
    id260: string | null // ID
  }
  jCnSiJOq: {
    // field return type
    id188: string | null // ID
  }
  jciWswYD: {
    // field return type
    id208: string | null // ID
  }
  jkcwiNhe: {
    // field return type
    id74: string | null // ID
  }
  jmnxoYAy: {
    // field return type
    id287: string | null // ID
  }
  jnFMLyxL: {
    // field return type
    id277: string | null // ID
  }
  jrmLpsfT: {
    // field return type
    id201: string | null // ID
  }
  kAFbqgpE: {
    // field return type
    id102: string | null // ID
  }
  kAqRlGFR: {
    // field return type
    id299: string | null // ID
  }
  kEhnOaCH: {
    // field return type
    id111: string | null // ID
  }
  kHLLmfcE: {
    // field return type
    id164: string | null // ID
  }
  kKQNulhi: {
    // field return type
    id5: string | null // ID
  }
  kQUqAggO: {
    // field return type
    id17: string | null // ID
  }
  kXMItaoE: {
    // field return type
    id154: string | null // ID
  }
  kkQiMyOg: {
    // field return type
    id33: string | null // ID
  }
  klkPkaYU: {
    // field return type
    id272: string | null // ID
  }
  lFbOnWGE: {
    // field return type
    id280: string | null // ID
  }
  lPtHeBuR: {
    // field return type
    id160: string | null // ID
  }
  lVumUBIa: {
    // field return type
    id174: string | null // ID
  }
  laqqtHJN: {
    // field return type
    id206: string | null // ID
  }
  ldqzvWyd: {
    // field return type
    id235: string | null // ID
  }
  lhdysNNV: {
    // field return type
    id71: string | null // ID
  }
  lifwEmKz: {
    // field return type
    id246: string | null // ID
  }
  lsDifAmH: {
    // field return type
    id298: string | null // ID
  }
  mFSUfTPi: {
    // field return type
    id116: string | null // ID
  }
  mKbKQhyO: {
    // field return type
    id167: string | null // ID
  }
  mQIYoGzu: {
    // field return type
    id28: string | null // ID
  }
  mZmlDoBs: {
    // field return type
    id273: string | null // ID
  }
  mooFGlVS: {
    // field return type
    id14: string | null // ID
  }
  mtikMWMb: {
    // field return type
    id261: string | null // ID
  }
  muuoinyp: {
    // field return type
    id70: string | null // ID
  }
  newdlmuf: {
    // field return type
    id39: string | null // ID
  }
  oLLKSNvK: {
    // field return type
    id176: string | null // ID
  }
  ogOIrhgb: {
    // field return type
    id47: string | null // ID
  }
  phBMkPER: {
    // field return type
    id236: string | null // ID
  }
  pnfpWCgc: {
    // field return type
    id99: string | null // ID
  }
  ptQOpnjR: {
    // field return type
    id190: string | null // ID
  }
  qBIjdcrW: {
    // field return type
    id142: string | null // ID
  }
  qCzvlwRD: {
    // field return type
    id80: string | null // ID
  }
  qXlhbRwq: {
    // field return type
    id78: string | null // ID
  }
  rDLkvRXw: {
    // field return type
    id296: string | null // ID
  }
  rKZaCTrp: {
    // field return type
    id89: string | null // ID
  }
  rsrjXXbp: {
    // field return type
    id267: string | null // ID
  }
  sOPJOCHV: {
    // field return type
    id108: string | null // ID
  }
  sYmZSZhS: {
    // field return type
    id45: string | null // ID
  }
  tBRvILTt: {
    // field return type
    id177: string | null // ID
  }
  tHuINsQQ: {
    // field return type
    id117: string | null // ID
  }
  tWYLhGmP: {
    // field return type
    id253: string | null // ID
  }
  tfdcstkI: {
    // field return type
    id262: string | null // ID
  }
  tgBSTWuP: {
    // field return type
    id40: string | null // ID
  }
  tndtDdZP: {
    // field return type
    id18: string | null // ID
  }
  uaVbWYYy: {
    // field return type
    id94: string | null // ID
  }
  ubXmVvgH: {
    // field return type
    id139: string | null // ID
  }
  unjJMyow: {
    // field return type
    id249: string | null // ID
  }
  uqAoXisC: {
    // field return type
    id9: string | null // ID
  }
  uxqOEIwV: {
    // field return type
    id49: string | null // ID
  }
  vKNwRocJ: {
    // field return type
    id229: string | null // ID
  }
  vWCRSMfI: {
    // field return type
    id37: string | null // ID
  }
  vmWUXlxn: {
    // field return type
    id233: string | null // ID
  }
  vveXjotS: {
    // field return type
    id11: string | null // ID
  }
  wYUTmKCU: {
    // field return type
    id291: string | null // ID
  }
  wtjYwstX: {
    // field return type
    id110: string | null // ID
  }
  wvbxCjzQ: {
    // field return type
    id131: string | null // ID
  }
  xHmRwgeG: {
    // field return type
    id42: string | null // ID
  }
  xUqWuwDO: {
    // field return type
    id288: string | null // ID
  }
  xnxcQfWx: {
    // field return type
    id76: string | null // ID
  }
  yJNnsHEj: {
    // field return type
    id135: string | null // ID
  }
  yJubHpPP: {
    // field return type
    id243: string | null // ID
  }
  yMjEoECr: {
    // field return type
    id196: string | null // ID
  }
  yNNQUmqa: {
    // field return type
    id150: string | null // ID
  }
  yNumRBxd: {
    // field return type
    id200: string | null // ID
  }
  yPDuKVOh: {
    // field return type
    id241: string | null // ID
  }
  yrGYxJeE: {
    // field return type
    id130: string | null // ID
  }
  yvlysvTB: {
    // field return type
    id269: string | null // ID
  }
  zLwooCNa: {
    // field return type
    id179: string | null // ID
  }
  zUQFahzk: {
    // field return type
    id283: string | null // ID
  }
  zjnLruIQ: {
    // field return type
    id289: string | null // ID
  }
  zlPOFwWi: {
    // field return type
    id183: string | null // ID
  }
  zpZvbHAk: {
    // field return type
    id124: string | null // ID
  }
  zvGUhtyF: {
    // field return type
    id186: string | null // ID
  }
}

export interface NexusGenArgTypes {}

export interface NexusGenAbstractResolveReturnTypes {
  BigUnion:
    | 'aEOOAAKG'
    | 'ahctkrlN'
    | 'aKYfIihK'
    | 'ALXAXBKq'
    | 'AOogKhAD'
    | 'ApAniugk'
    | 'AQDzZPsI'
    | 'arOfyZvi'
    | 'AuMxHAoX'
    | 'awDoUlrM'
    | 'BAzfAeMR'
    | 'bdmjhrZP'
    | 'BFohGIGQ'
    | 'bGRbQdGF'
    | 'BiZjyuaY'
    | 'Bjgguvhd'
    | 'bLcHZPpX'
    | 'bNaHPVhI'
    | 'bndWrLAg'
    | 'bpcReAKs'
    | 'bsuhpkhX'
    | 'BTIsXTrL'
    | 'BWwxnXpM'
    | 'BXowGvwZ'
    | 'BYPWzETJ'
    | 'CCXSFsMn'
    | 'cEORMlXC'
    | 'CgAQHanX'
    | 'cGxDWUGD'
    | 'cMxjKIfV'
    | 'ctfzshTJ'
    | 'cXAmxvqv'
    | 'CXumheDD'
    | 'dAmPEeQn'
    | 'dbFplbat'
    | 'DbgPTfDo'
    | 'DBZLsxpr'
    | 'deqJYjdv'
    | 'DGxuhtpo'
    | 'dHKrfYNo'
    | 'DKEJFUiy'
    | 'DkoAlvGn'
    | 'DMggicLd'
    | 'dnjGpfIS'
    | 'DNohRdIN'
    | 'dnutiEie'
    | 'dOWdqEud'
    | 'DpnWHIJW'
    | 'ECChhDfK'
    | 'eemljdwg'
    | 'eggnlUYr'
    | 'EhpNnQJw'
    | 'EjIQIfmv'
    | 'eJSSQaaC'
    | 'EqEZXLCy'
    | 'eROeesVg'
    | 'EtPHwkkm'
    | 'ETUiuOHD'
    | 'euCWAGET'
    | 'eWlLfMzi'
    | 'EzcWBhIv'
    | 'FaJAYKqm'
    | 'faKaQEBn'
    | 'FcFlCNAk'
    | 'fDAloqko'
    | 'FDouQoXO'
    | 'fFyvwcxZ'
    | 'FHLtgKoA'
    | 'fPXYtcbT'
    | 'FvftqquW'
    | 'fvXQFkRb'
    | 'fXnweaVk'
    | 'GcpbGXTn'
    | 'GDATeumz'
    | 'GdxXCAak'
    | 'gfyuMPLk'
    | 'GhHKLcZe'
    | 'gQDQWruj'
    | 'gqhvwsiF'
    | 'GsbHZkLK'
    | 'gvxFkejN'
    | 'GwkBnXKj'
    | 'GYbaqoRT'
    | 'GzglazdH'
    | 'hAfKmdaD'
    | 'hBCadJbD'
    | 'HdiyXGxs'
    | 'hDsbddpo'
    | 'HENcJewx'
    | 'hEyyqHvv'
    | 'hgsVEiUk'
    | 'HgYVPDgm'
    | 'hIjYlIps'
    | 'HIPZQFdS'
    | 'HJmsvtgX'
    | 'HjRDJhnX'
    | 'hLptFSis'
    | 'HLRWzsTU'
    | 'HNLQTErw'
    | 'hOqSbuBE'
    | 'hQiYNmDV'
    | 'hqweSGgf'
    | 'hTNuohNQ'
    | 'HwkXtjRP'
    | 'HWMyawvm'
    | 'HxCkBUxv'
    | 'HXZUTyvG'
    | 'HZbsVdoX'
    | 'IAOEaBfb'
    | 'IBZxPcZb'
    | 'ICrkovFe'
    | 'IGibGxHO'
    | 'IhSGxaNc'
    | 'IhtaZNUi'
    | 'iqXgPwiC'
    | 'IqZAiUKE'
    | 'ISayJMYD'
    | 'IuVQPFJN'
    | 'iVjcPoMw'
    | 'IWhegzTM'
    | 'iWpPsvNV'
    | 'ixwjWVvf'
    | 'Iypygftg'
    | 'IZERvBgk'
    | 'iZJAoMWm'
    | 'jAUaKDuu'
    | 'JbsCxxcE'
    | 'jciWswYD'
    | 'jCnSiJOq'
    | 'JjkgZKrV'
    | 'jkcwiNhe'
    | 'jmnxoYAy'
    | 'jnFMLyxL'
    | 'jrmLpsfT'
    | 'JsAPYbRs'
    | 'JuaucwDY'
    | 'JXAbemqC'
    | 'JZMQpjQv'
    | 'kAFbqgpE'
    | 'kAqRlGFR'
    | 'KbTYPbTr'
    | 'kEhnOaCH'
    | 'KGbJMfhO'
    | 'kHLLmfcE'
    | 'kkQiMyOg'
    | 'kKQNulhi'
    | 'klkPkaYU'
    | 'KoKtAqbt'
    | 'kQUqAggO'
    | 'KsPfaUFr'
    | 'KvHHVcPa'
    | 'KVIgujkc'
    | 'kXMItaoE'
    | 'laqqtHJN'
    | 'LBePcCkW'
    | 'ldqzvWyd'
    | 'lFbOnWGE'
    | 'lhdysNNV'
    | 'LHxWkxKq'
    | 'lifwEmKz'
    | 'LMnZbpCI'
    | 'lPtHeBuR'
    | 'lsDifAmH'
    | 'LtvKCzwe'
    | 'lVumUBIa'
    | 'mFSUfTPi'
    | 'mKbKQhyO'
    | 'mooFGlVS'
    | 'MPQLFUho'
    | 'mQIYoGzu'
    | 'mtikMWMb'
    | 'muuoinyp'
    | 'MvpRfuhb'
    | 'mZmlDoBs'
    | 'NbTtwcUU'
    | 'NczZcGdE'
    | 'NefQmhqG'
    | 'NETQHyFQ'
    | 'newdlmuf'
    | 'NlMnyCgu'
    | 'NrrBYDim'
    | 'NwPaWUGr'
    | 'OBnGIgyZ'
    | 'OehdOjXt'
    | 'OfyEZrPd'
    | 'ogOIrhgb'
    | 'OjwpvBGH'
    | 'oLLKSNvK'
    | 'OwZeKGSU'
    | 'OZfGULVa'
    | 'PBGQfXYx'
    | 'PGcwRfdb'
    | 'phBMkPER'
    | 'PHltFHbS'
    | 'PNeiVzWR'
    | 'pnfpWCgc'
    | 'PNgZWWwo'
    | 'PpTuFbFz'
    | 'ptQOpnjR'
    | 'PTtcHGFZ'
    | 'PVCfSccj'
    | 'PWOXDRzE'
    | 'PwzFJfRE'
    | 'PYCDIQQc'
    | 'qBIjdcrW'
    | 'qCzvlwRD'
    | 'QelISHAj'
    | 'QKdnhgbW'
    | 'QMkOOMdT'
    | 'QmPQoOZh'
    | 'QxHzTNGy'
    | 'qXlhbRwq'
    | 'QXSXwpMN'
    | 'RCZmHSOp'
    | 'rDLkvRXw'
    | 'rKZaCTrp'
    | 'RMBiaCdu'
    | 'RNSfiIOi'
    | 'rsrjXXbp'
    | 'RTcWEgoC'
    | 'RVbkKVjJ'
    | 'RydRYmBj'
    | 'SBNNVkRr'
    | 'ShqdAPLQ'
    | 'sOPJOCHV'
    | 'SsKBGyvg'
    | 'Stydvxig'
    | 'sYmZSZhS'
    | 'TbgzaUgu'
    | 'tBRvILTt'
    | 'TDURJGny'
    | 'TDztrYLm'
    | 'TeZWMTzw'
    | 'tfdcstkI'
    | 'tgBSTWuP'
    | 'tHuINsQQ'
    | 'TKzetlpb'
    | 'tndtDdZP'
    | 'TppFHtyg'
    | 'TWLZYGzk'
    | 'tWYLhGmP'
    | 'TZHgNTAO'
    | 'uaVbWYYy'
    | 'ubXmVvgH'
    | 'UGJqdGDT'
    | 'unjJMyow'
    | 'uqAoXisC'
    | 'UuNFAnQg'
    | 'uxqOEIwV'
    | 'VAvPoGEb'
    | 'vKNwRocJ'
    | 'vmWUXlxn'
    | 'vveXjotS'
    | 'vWCRSMfI'
    | 'VynhbqCL'
    | 'WaVLDFqC'
    | 'WhUVndTD'
    | 'WMsrUAGp'
    | 'WoCNZkWp'
    | 'WsneBHrs'
    | 'WsNuPHEi'
    | 'wtjYwstX'
    | 'WurxotQy'
    | 'wvbxCjzQ'
    | 'wYUTmKCU'
    | 'XdzKjpVP'
    | 'XFYbFCkA'
    | 'xHmRwgeG'
    | 'XHvdKJbC'
    | 'xnxcQfWx'
    | 'Xqkpjqni'
    | 'xUqWuwDO'
    | 'XvyULguR'
    | 'XwweqpQZ'
    | 'YBZmfmWn'
    | 'yJNnsHEj'
    | 'yJubHpPP'
    | 'yMjEoECr'
    | 'YNnosqXJ'
    | 'yNNQUmqa'
    | 'yNumRBxd'
    | 'yPDuKVOh'
    | 'yrGYxJeE'
    | 'yvlysvTB'
    | 'YwFARARB'
    | 'YxNVEAVR'
    | 'YZpErVkH'
    | 'ZbrxBPat'
    | 'ZElcDXRS'
    | 'ZeyczKBv'
    | 'ZEyINaeG'
    | 'zjnLruIQ'
    | 'zlPOFwWi'
    | 'zLwooCNa'
    | 'zpZvbHAk'
    | 'ZrPlFevQ'
    | 'zUQFahzk'
    | 'ZVaYkAdb'
    | 'zvGUhtyF'
    | 'ZzRSmAyf'
  MediumUnionType:
    | 'AOogKhAD'
    | 'ApAniugk'
    | 'AuMxHAoX'
    | 'awDoUlrM'
    | 'bGRbQdGF'
    | 'bsuhpkhX'
    | 'BXowGvwZ'
    | 'CgAQHanX'
    | 'cMxjKIfV'
    | 'cXAmxvqv'
    | 'dAmPEeQn'
    | 'DBZLsxpr'
    | 'deqJYjdv'
    | 'dnjGpfIS'
    | 'dnutiEie'
    | 'dOWdqEud'
    | 'ECChhDfK'
    | 'eggnlUYr'
    | 'EhpNnQJw'
    | 'EjIQIfmv'
    | 'eJSSQaaC'
    | 'EtPHwkkm'
    | 'FaJAYKqm'
    | 'fvXQFkRb'
    | 'fXnweaVk'
    | 'GYbaqoRT'
    | 'GzglazdH'
    | 'hBCadJbD'
    | 'HgYVPDgm'
    | 'HjRDJhnX'
    | 'hLptFSis'
    | 'hQiYNmDV'
    | 'hqweSGgf'
    | 'HwkXtjRP'
    | 'HZbsVdoX'
    | 'IAOEaBfb'
    | 'ICrkovFe'
    | 'IhSGxaNc'
    | 'ISayJMYD'
    | 'iVjcPoMw'
    | 'ixwjWVvf'
    | 'Iypygftg'
    | 'iZJAoMWm'
    | 'jkcwiNhe'
    | 'JuaucwDY'
    | 'JZMQpjQv'
    | 'kAFbqgpE'
    | 'KbTYPbTr'
    | 'kEhnOaCH'
    | 'KsPfaUFr'
    | 'KvHHVcPa'
    | 'LBePcCkW'
    | 'lhdysNNV'
    | 'LHxWkxKq'
    | 'LMnZbpCI'
    | 'mFSUfTPi'
    | 'muuoinyp'
    | 'NefQmhqG'
    | 'NETQHyFQ'
    | 'OwZeKGSU'
    | 'PBGQfXYx'
    | 'PGcwRfdb'
    | 'PNeiVzWR'
    | 'pnfpWCgc'
    | 'PNgZWWwo'
    | 'PTtcHGFZ'
    | 'PWOXDRzE'
    | 'PwzFJfRE'
    | 'qBIjdcrW'
    | 'qCzvlwRD'
    | 'QelISHAj'
    | 'QMkOOMdT'
    | 'qXlhbRwq'
    | 'rKZaCTrp'
    | 'RMBiaCdu'
    | 'RNSfiIOi'
    | 'sOPJOCHV'
    | 'SsKBGyvg'
    | 'TbgzaUgu'
    | 'tHuINsQQ'
    | 'TppFHtyg'
    | 'TWLZYGzk'
    | 'uaVbWYYy'
    | 'ubXmVvgH'
    | 'UGJqdGDT'
    | 'WaVLDFqC'
    | 'WhUVndTD'
    | 'WoCNZkWp'
    | 'WsneBHrs'
    | 'wtjYwstX'
    | 'WurxotQy'
    | 'wvbxCjzQ'
    | 'XFYbFCkA'
    | 'xnxcQfWx'
    | 'XvyULguR'
    | 'YBZmfmWn'
    | 'yJNnsHEj'
    | 'yrGYxJeE'
    | 'ZEyINaeG'
    | 'zpZvbHAk'
  MediumUnionTypes:
    | 'ALXAXBKq'
    | 'AOogKhAD'
    | 'ApAniugk'
    | 'bdmjhrZP'
    | 'BiZjyuaY'
    | 'bpcReAKs'
    | 'bsuhpkhX'
    | 'BXowGvwZ'
    | 'CgAQHanX'
    | 'cXAmxvqv'
    | 'dAmPEeQn'
    | 'dHKrfYNo'
    | 'dnutiEie'
    | 'dOWdqEud'
    | 'DpnWHIJW'
    | 'ECChhDfK'
    | 'eemljdwg'
    | 'EqEZXLCy'
    | 'eROeesVg'
    | 'EtPHwkkm'
    | 'ETUiuOHD'
    | 'FaJAYKqm'
    | 'fDAloqko'
    | 'fXnweaVk'
    | 'GdxXCAak'
    | 'gQDQWruj'
    | 'gqhvwsiF'
    | 'GsbHZkLK'
    | 'GzglazdH'
    | 'HgYVPDgm'
    | 'hLptFSis'
    | 'hOqSbuBE'
    | 'hqweSGgf'
    | 'HwkXtjRP'
    | 'HXZUTyvG'
    | 'HZbsVdoX'
    | 'ICrkovFe'
    | 'IWhegzTM'
    | 'ixwjWVvf'
    | 'Iypygftg'
    | 'IZERvBgk'
    | 'JbsCxxcE'
    | 'jkcwiNhe'
    | 'KbTYPbTr'
    | 'kkQiMyOg'
    | 'kKQNulhi'
    | 'kQUqAggO'
    | 'KsPfaUFr'
    | 'lhdysNNV'
    | 'LHxWkxKq'
    | 'LtvKCzwe'
    | 'mooFGlVS'
    | 'MPQLFUho'
    | 'mQIYoGzu'
    | 'muuoinyp'
    | 'NbTtwcUU'
    | 'NETQHyFQ'
    | 'newdlmuf'
    | 'OfyEZrPd'
    | 'ogOIrhgb'
    | 'PBGQfXYx'
    | 'PGcwRfdb'
    | 'pnfpWCgc'
    | 'PpTuFbFz'
    | 'PWOXDRzE'
    | 'PwzFJfRE'
    | 'PYCDIQQc'
    | 'qCzvlwRD'
    | 'QelISHAj'
    | 'QKdnhgbW'
    | 'qXlhbRwq'
    | 'RCZmHSOp'
    | 'rKZaCTrp'
    | 'RMBiaCdu'
    | 'RNSfiIOi'
    | 'RTcWEgoC'
    | 'SsKBGyvg'
    | 'sYmZSZhS'
    | 'TDURJGny'
    | 'TDztrYLm'
    | 'tgBSTWuP'
    | 'tndtDdZP'
    | 'TppFHtyg'
    | 'TWLZYGzk'
    | 'uaVbWYYy'
    | 'UGJqdGDT'
    | 'uqAoXisC'
    | 'uxqOEIwV'
    | 'vveXjotS'
    | 'vWCRSMfI'
    | 'VynhbqCL'
    | 'WurxotQy'
    | 'XdzKjpVP'
    | 'XFYbFCkA'
    | 'xHmRwgeG'
    | 'xnxcQfWx'
    | 'Xqkpjqni'
    | 'YBZmfmWn'
    | 'ZeyczKBv'
    | 'ZEyINaeG'
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames =
  | 'ALXAXBKq'
  | 'AOogKhAD'
  | 'AQDzZPsI'
  | 'ApAniugk'
  | 'AuMxHAoX'
  | 'BAzfAeMR'
  | 'BFohGIGQ'
  | 'BTIsXTrL'
  | 'BWwxnXpM'
  | 'BXowGvwZ'
  | 'BYPWzETJ'
  | 'BiZjyuaY'
  | 'Bjgguvhd'
  | 'CCXSFsMn'
  | 'CXumheDD'
  | 'CgAQHanX'
  | 'DBZLsxpr'
  | 'DGxuhtpo'
  | 'DKEJFUiy'
  | 'DMggicLd'
  | 'DNohRdIN'
  | 'DbgPTfDo'
  | 'DkoAlvGn'
  | 'DpnWHIJW'
  | 'ECChhDfK'
  | 'ETUiuOHD'
  | 'EhpNnQJw'
  | 'EjIQIfmv'
  | 'EqEZXLCy'
  | 'EtPHwkkm'
  | 'EzcWBhIv'
  | 'FDouQoXO'
  | 'FHLtgKoA'
  | 'FaJAYKqm'
  | 'FcFlCNAk'
  | 'FvftqquW'
  | 'GDATeumz'
  | 'GYbaqoRT'
  | 'GcpbGXTn'
  | 'GdxXCAak'
  | 'GhHKLcZe'
  | 'GsbHZkLK'
  | 'GwkBnXKj'
  | 'GzglazdH'
  | 'HENcJewx'
  | 'HIPZQFdS'
  | 'HJmsvtgX'
  | 'HLRWzsTU'
  | 'HNLQTErw'
  | 'HWMyawvm'
  | 'HXZUTyvG'
  | 'HZbsVdoX'
  | 'HdiyXGxs'
  | 'HgYVPDgm'
  | 'HjRDJhnX'
  | 'HwkXtjRP'
  | 'HxCkBUxv'
  | 'IAOEaBfb'
  | 'IBZxPcZb'
  | 'ICrkovFe'
  | 'IGibGxHO'
  | 'ISayJMYD'
  | 'IWhegzTM'
  | 'IZERvBgk'
  | 'IhSGxaNc'
  | 'IhtaZNUi'
  | 'IqZAiUKE'
  | 'IuVQPFJN'
  | 'Iypygftg'
  | 'JXAbemqC'
  | 'JZMQpjQv'
  | 'JbsCxxcE'
  | 'JjkgZKrV'
  | 'JsAPYbRs'
  | 'JuaucwDY'
  | 'KGbJMfhO'
  | 'KVIgujkc'
  | 'KbTYPbTr'
  | 'KoKtAqbt'
  | 'KsPfaUFr'
  | 'KvHHVcPa'
  | 'LBePcCkW'
  | 'LHxWkxKq'
  | 'LMnZbpCI'
  | 'LtvKCzwe'
  | 'MPQLFUho'
  | 'MvpRfuhb'
  | 'NETQHyFQ'
  | 'NbTtwcUU'
  | 'NczZcGdE'
  | 'NefQmhqG'
  | 'NlMnyCgu'
  | 'NrrBYDim'
  | 'NwPaWUGr'
  | 'OBnGIgyZ'
  | 'OZfGULVa'
  | 'OehdOjXt'
  | 'OfyEZrPd'
  | 'OjwpvBGH'
  | 'OwZeKGSU'
  | 'PBGQfXYx'
  | 'PGcwRfdb'
  | 'PHltFHbS'
  | 'PNeiVzWR'
  | 'PNgZWWwo'
  | 'PTtcHGFZ'
  | 'PVCfSccj'
  | 'PWOXDRzE'
  | 'PYCDIQQc'
  | 'PpTuFbFz'
  | 'PwzFJfRE'
  | 'QKdnhgbW'
  | 'QMkOOMdT'
  | 'QXSXwpMN'
  | 'QelISHAj'
  | 'QmPQoOZh'
  | 'Query'
  | 'QxHzTNGy'
  | 'RCZmHSOp'
  | 'RMBiaCdu'
  | 'RNSfiIOi'
  | 'RTcWEgoC'
  | 'RVbkKVjJ'
  | 'RydRYmBj'
  | 'SBNNVkRr'
  | 'ShqdAPLQ'
  | 'SsKBGyvg'
  | 'Stydvxig'
  | 'TDURJGny'
  | 'TDztrYLm'
  | 'TKzetlpb'
  | 'TWLZYGzk'
  | 'TZHgNTAO'
  | 'TbgzaUgu'
  | 'TeZWMTzw'
  | 'TppFHtyg'
  | 'UGJqdGDT'
  | 'UuNFAnQg'
  | 'VAvPoGEb'
  | 'VynhbqCL'
  | 'WMsrUAGp'
  | 'WaVLDFqC'
  | 'WhUVndTD'
  | 'WoCNZkWp'
  | 'WsNuPHEi'
  | 'WsneBHrs'
  | 'WurxotQy'
  | 'XFYbFCkA'
  | 'XHvdKJbC'
  | 'XdzKjpVP'
  | 'Xqkpjqni'
  | 'XvyULguR'
  | 'XwweqpQZ'
  | 'YBZmfmWn'
  | 'YNnosqXJ'
  | 'YZpErVkH'
  | 'YwFARARB'
  | 'YxNVEAVR'
  | 'ZElcDXRS'
  | 'ZEyINaeG'
  | 'ZVaYkAdb'
  | 'ZbrxBPat'
  | 'ZeyczKBv'
  | 'ZrPlFevQ'
  | 'ZzRSmAyf'
  | 'aEOOAAKG'
  | 'aKYfIihK'
  | 'ahctkrlN'
  | 'arOfyZvi'
  | 'awDoUlrM'
  | 'bGRbQdGF'
  | 'bLcHZPpX'
  | 'bNaHPVhI'
  | 'bdmjhrZP'
  | 'bndWrLAg'
  | 'bpcReAKs'
  | 'bsuhpkhX'
  | 'cEORMlXC'
  | 'cGxDWUGD'
  | 'cMxjKIfV'
  | 'cXAmxvqv'
  | 'ctfzshTJ'
  | 'dAmPEeQn'
  | 'dHKrfYNo'
  | 'dOWdqEud'
  | 'dbFplbat'
  | 'deqJYjdv'
  | 'dnjGpfIS'
  | 'dnutiEie'
  | 'eJSSQaaC'
  | 'eROeesVg'
  | 'eWlLfMzi'
  | 'eemljdwg'
  | 'eggnlUYr'
  | 'euCWAGET'
  | 'fDAloqko'
  | 'fFyvwcxZ'
  | 'fPXYtcbT'
  | 'fXnweaVk'
  | 'faKaQEBn'
  | 'fvXQFkRb'
  | 'gQDQWruj'
  | 'gfyuMPLk'
  | 'gqhvwsiF'
  | 'gvxFkejN'
  | 'hAfKmdaD'
  | 'hBCadJbD'
  | 'hDsbddpo'
  | 'hEyyqHvv'
  | 'hIjYlIps'
  | 'hLptFSis'
  | 'hOqSbuBE'
  | 'hQiYNmDV'
  | 'hTNuohNQ'
  | 'hgsVEiUk'
  | 'hqweSGgf'
  | 'iVjcPoMw'
  | 'iWpPsvNV'
  | 'iZJAoMWm'
  | 'iqXgPwiC'
  | 'ixwjWVvf'
  | 'jAUaKDuu'
  | 'jCnSiJOq'
  | 'jciWswYD'
  | 'jkcwiNhe'
  | 'jmnxoYAy'
  | 'jnFMLyxL'
  | 'jrmLpsfT'
  | 'kAFbqgpE'
  | 'kAqRlGFR'
  | 'kEhnOaCH'
  | 'kHLLmfcE'
  | 'kKQNulhi'
  | 'kQUqAggO'
  | 'kXMItaoE'
  | 'kkQiMyOg'
  | 'klkPkaYU'
  | 'lFbOnWGE'
  | 'lPtHeBuR'
  | 'lVumUBIa'
  | 'laqqtHJN'
  | 'ldqzvWyd'
  | 'lhdysNNV'
  | 'lifwEmKz'
  | 'lsDifAmH'
  | 'mFSUfTPi'
  | 'mKbKQhyO'
  | 'mQIYoGzu'
  | 'mZmlDoBs'
  | 'mooFGlVS'
  | 'mtikMWMb'
  | 'muuoinyp'
  | 'newdlmuf'
  | 'oLLKSNvK'
  | 'ogOIrhgb'
  | 'phBMkPER'
  | 'pnfpWCgc'
  | 'ptQOpnjR'
  | 'qBIjdcrW'
  | 'qCzvlwRD'
  | 'qXlhbRwq'
  | 'rDLkvRXw'
  | 'rKZaCTrp'
  | 'rsrjXXbp'
  | 'sOPJOCHV'
  | 'sYmZSZhS'
  | 'tBRvILTt'
  | 'tHuINsQQ'
  | 'tWYLhGmP'
  | 'tfdcstkI'
  | 'tgBSTWuP'
  | 'tndtDdZP'
  | 'uaVbWYYy'
  | 'ubXmVvgH'
  | 'unjJMyow'
  | 'uqAoXisC'
  | 'uxqOEIwV'
  | 'vKNwRocJ'
  | 'vWCRSMfI'
  | 'vmWUXlxn'
  | 'vveXjotS'
  | 'wYUTmKCU'
  | 'wtjYwstX'
  | 'wvbxCjzQ'
  | 'xHmRwgeG'
  | 'xUqWuwDO'
  | 'xnxcQfWx'
  | 'yJNnsHEj'
  | 'yJubHpPP'
  | 'yMjEoECr'
  | 'yNNQUmqa'
  | 'yNumRBxd'
  | 'yPDuKVOh'
  | 'yrGYxJeE'
  | 'yvlysvTB'
  | 'zLwooCNa'
  | 'zUQFahzk'
  | 'zjnLruIQ'
  | 'zlPOFwWi'
  | 'zpZvbHAk'
  | 'zvGUhtyF'

export type NexusGenInputNames = never

export type NexusGenEnumNames = never

export type NexusGenInterfaceNames = never

export type NexusGenScalarNames = 'Boolean' | 'Float' | 'ID' | 'Int' | 'String'

export type NexusGenUnionNames = 'BigUnion' | 'MediumUnionType' | 'MediumUnionTypes'

export interface NexusGenTypes {
  context: any
  inputTypes: NexusGenInputs
  rootTypes: NexusGenRootTypes
  argTypes: NexusGenArgTypes
  fieldTypes: NexusGenFieldTypes
  allTypes: NexusGenAllTypes
  inheritedFields: NexusGenInheritedFields
  objectNames: NexusGenObjectNames
  inputNames: NexusGenInputNames
  enumNames: NexusGenEnumNames
  interfaceNames: NexusGenInterfaceNames
  scalarNames: NexusGenScalarNames
  unionNames: NexusGenUnionNames
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames']
  allOutputTypes:
    | NexusGenTypes['objectNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['unionNames']
    | NexusGenTypes['interfaceNames']
    | NexusGenTypes['scalarNames']
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames']
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes
}

declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {}
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {}
  interface NexusGenPluginSchemaConfig {}
}
