import { dedent } from "./utils";

export const SDL_HEADER = dedent`
  ### ---
  ### This file was autogenerated by graphqliteral
  ### Do not edit the contents directly
  ### ---
`;

export const TYPEGEN_HEADER = dedent`
  /**
   * This file is automatically generated. Do not make changes directly.
   * 
   * By default this will regenerate when the server is started 
   * and NODE_ENV !== "production".
   * 
   * Mostly for internal use by GraphQLiteral unless otherwise 
   * documented / subject to change.
   * 
   * If you want more configurable types to use elsewhere, look into one of:
   *
   * https://github.com/dotansimha/graphql-code-generator
   * https://github.com/prisma/graphqlgen
   * https://github.com/apollographql/apollo-tooling
   */
`;
