const { version } = require("../package.json");

export const SDL_HEADER = `### This file was autogenerated by Nexus ${version}
### Do not make changes to this file directly
`;

export const TYPEGEN_HEADER = `/**
 * This file was automatically generated by Nexus ${version}
 * Do not make changes to this file directly
 */
`;

export const TYPEGEN_CONFIG_WARNING = `/**
 * For better typings, you should provide configuration for how to lookup 
 * the types. See the documentation for "typegenAutoConfig"
 */
`;
